### ISSUE TITLE
Max size of image

### ISSUE THREAD

**Issue by eNepper** [Automattic/node-canvas#1082] opened 2018-01-29 14:21 UTC
Hi

Is there a max size on image?
I trying to set the src paramter of an image to a buffer containing an 28086x19866 px image and my node app just quits after that, no error no nothing.

-- Esben N.

**Comment by zbjornson** [comment] 2018-01-29 18:49
I think the max image size is 32,767 px in either dimension, but you're likely hitting some allocation failure for the format parser. What type of image is in the buffer (PNG, GIF, JPEG, SVG)?

**Comment by eNepper** [comment] 2018-01-29 21:45
If I'm not mistaken it's a PNG image.

**Comment by zbjornson** [comment] 2018-01-29 22:06
I just successfully loaded a 1.45GB PNG (28,000 x 18,666 px).

```js
const fs = require("fs");
const {Image} = require("./index");

const buff = fs.readFileSync("big.png");
console.log(buff.byteLength);

const img = new Image();
img.src = buff;
console.log(img);
```

Any more info you can provide?

**Comment by eNepper** [comment] 2018-01-29 22:20
It's another canvas I'm turning in to an image not sure if that any different.
I also tried to reuse the canvas but then I get this error: GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Comment by eNepper** [comment] 2018-01-29 22:25
The canvas buffer is "only" 24092988 bytes long :/

**Comment by zbjornson** [comment] 2018-01-29 22:27
Can you post a short code example that reproduces it please?

If the error is in some use of GLib then I might have missed it by trying to reproduce it on Windows. I can try on linux later.

**Comment by eNepper** [comment] 2018-01-29 22:32
I'll see if I can create a sample that reproduces this that I'm able to share with you. 
I'm running it on a Ubuntu 17.10 with Node v8.9.4

**Comment by eNepper** [comment] 2018-01-30 07:17
After hooking up the onerror on image I get this error: "Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)"

**Comment by zbjornson** [comment] 2018-01-30 07:27
That's a Cairo message/limitation that we can't do anything about. In the Cairo source I only see it raised if there is one dimension >32767 px (or <=0) though, which is larger than the dimensions you mentioned...

**Comment by eNepper** [comment] 2018-01-30 07:57
I found a mistake I made trying to set the src to a PDF canvas buffer, but I'm getting "Error: out of memory" now

**Comment by eNepper** [comment] 2018-01-30 11:59
const { createCanvas, Image } = require('canvas');
const fs = require('fs');

const size = { width: 28086, height: 19866 };

let base = new Promise((resolve, reject) => {
    let canvas = createCanvas(size.width, size.height);
    let ctx = canvas.getContext('2d');

    let gradient = ctx.createLinearGradient(0, 0, size.width, size.height);
    gradient.addColorStop(0, '#8FBC8F');
    gradient.addColorStop(0.25, '#BA55D3');
    gradient.addColorStop(0.5, '#FF00FF');
    gradient.addColorStop(0.75, '#7CFC00');
    gradient.addColorStop(1, '#00BFFF');

    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, size.width, size.height);

    resolve(canvas.toBuffer());
});

let overlay = new Promise((resolve, reject) => {
    let canvas = createCanvas(size.width, size.height);
    let ctx = canvas.getContext('2d');

    ctx.beginPath();
    ctx.arc(size.width / 2, size.height / 2, size.width / 4, 0, 2 * Math.PI);
    ctx.fillStyle = '#9932CC';
    ctx.fill();

    resolve(canvas.toBuffer());
});


Promise.all([base, overlay]).then(layers => {
    return new Promise((resolve, reject) => {
        let canvas = createCanvas(size.width, size.height);
        let ctx = canvas.getContext('2d');
        let img = new Image();
        img.onload = _ => {
            ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
            img.src = null;
            if (layers.length > 0) {
                drawLayers(layers);
            } else {
                resolve(canvas);
            }
        };
        img.onerror = (err) => {
            console.log(err.toString());
        };
        

        drawLayers(layers.reverse());

        function drawLayers(layers) {
            img.src = layers.pop();
        }
    });
}).then(canvas => {
    fs.writeFile(`issue-#1082.png`, canvas.toBuffer(), function (err) {
        if (err) throw err;
    });
});

This code results in a "Error: out of memory" on my machine, which I don't get why as  I got 16 gigs and the usages is no more than 40%.

**Comment by eNepper** [comment] 2018-01-30 19:28
The sample resembles the structure of the code I'm working on but base is a layer of image tiles from another process which I'm stitching together before rendering an overlay on top from SVG data. I working on parallelizing the processes as much as possible to cut down process time. 

Yes I'm running on 64bit 

I'll look into implementing some of your recommendations.

**Comment by zbjornson** [comment] 2018-02-14 21:38
Closing since I don't think there's anything we can do within node-canvas...

**Closed by zbjornson** 2018-02-14 21:38 UTC
