### ISSUE TITLE
Can not install Canvas through npm on Synology NAS

### ISSUE THREAD

**Issue by Leavoh** [Automattic/node-canvas#1969] opened 2022-01-10 13:40 UTC
## Never had issues with NPM installations before, and I didn't really understand the information about pre-build things, I am on a Synology NAS, which is quite a closed environment, so dunno what to do if a simple npm command doesn't work.

ash-4.4# npm i canvas
npm ERR! code 1
npm ERR! path /volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/volume1/@appstore/nodejs_v16/bin/node /volume1/@appstore/nodejs_v16/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.8
npm ERR! node-pre-gyp info using node@16.13.1 | linux | x64
npm ERR! node-pre-gyp info check checked for "/volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/canvas/build/Release/canvas.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-linux-unknown-x64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-linux-unknown-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.8.0 and node@16.13.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.8.0/canvas-v2.8.0-node-v93-linux-unknown-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.1 | linux | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.8 found at "/bin/python3"
npm ERR! gyp WARN EACCES current user ("Livo") does not have permission to access the dev dir "/root/.cache/node-gyp/16.13.1"
npm ERR! gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
npm ERR! gyp info spawn /bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/volume1/@appstore/nodejs_v16/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/volume1/@appstore/nodejs_v16/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/tmp/.node-gyp/16.13.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/tmp/.node-gyp/16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/volume1/@appstore/nodejs_v16/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/tmp/.node-gyp/16.13.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: pkg-config: command not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/volume1/@appstore/nodejs_v16/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 4.4.180+
npm ERR! gyp ERR! command "/volume1/@appstore/nodejs_v16/bin/node" "/volume1/@appstore/nodejs_v16/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/canvas
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/volume1/@appstore/nodejs_v16/bin/node /volume1/@appstore/nodejs_v16/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Linux 4.4.180+
npm ERR! node-pre-gyp ERR! command "/volume1/@appstore/nodejs_v16/bin/node" "/volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /volume2/Livo/Development/Discord Bots/Inquisitors - Canvas version/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v16.13.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.8
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-10T13_20_34_125Z-debug.log

## Steps to Reproduce
sudo su
npm i canvas

## Your Environment
* npm -v: 8.1.2
* node -v: v16.13.1

**Comment by LinusU** [comment] 2022-01-10 15:40
Duplicate of #1968

**Closed by LinusU** 2022-01-10 15:40 UTC
