### ISSUE TITLE
How to tell Canvas.pngStream() that the stream has ended?

### ISSUE THREAD

**Issue by giacecco** [Automattic/node-canvas#351] opened 2013-10-30 11:46 UTC
Sorry if this is a stupid question, but I can't find a solution. If I write code like the one you see below:

		var canvas = new Canvas(CARD_SIZE_X, CARD_SIZE_Y),
			out = fs.createWriteStream(__dirname + '/text' + page + '.png'),
			stream = canvas.pngStream(),
		  	ctx = canvas.getContext('2d');
		stream.on('data', function(chunk) { out.write(chunk); });
		stream.on('end', function() { console.log('saved png'); });

... the 'end' event of the stream is triggered when the nodejs script exits. 

What method of stream or perhaps canvas should I call if I need the stream to end before that, e.g. if I want to use the file that I have just created within the same script?

Moreover, if I create many streams from different canvas, when execution ends only the last of the .png files I have created has content, while all other files have zero length.

Thanks,

Giacecco

**Comment by LinusU** [comment] 2016-02-15 20:23
Closing this since it's an old thread, please report back if you still have problems...

**Closed by LinusU** 2016-02-15 20:23 UTC

**Comment by Etsitpab** [comment] 2016-02-29 20:10
I still have the same problem with jpeg streams. The end event is only triggered when the script ends. This makes it consumming a lot of memory.

**Comment by LinusU** [comment] 2016-02-29 20:45
@Etsitpab That does sound like a bug, but I don't think it's the same since JPEG- and PNG-streams are handled very differently. Could you open up a new bug describing your issue?

**Comment by Etsitpab** [comment] 2016-03-07 12:09
@LinusU sorry for the delay, here is the shortest script I could write to reproduce the problem I observed :

```
#!/usr/bin/env node

var fs = require('fs'),
    Canvas = require('canvas'),
    Image = Canvas.Image;

(function () {
    "use strict";
    var out, stream;
    out = fs.createWriteStream("test1.jpg");
    stream = new Canvas(500, 500).syncJPEGStream();
    stream.on('data', function (chunk) {
        console.log("Write chunk for", "test1.jpg")
        out.write(chunk);
    });
    stream.on('end', function () {
        console.log("End stream for", "test1.jpg")
    });
    out = fs.createWriteStream("test2.jpg");
    stream = new Canvas(500, 500).syncJPEGStream();
    stream.on('data', function (chunk) {
        console.log("Write chunk for", "test2.jpg")
        out.write(chunk);
    });
    stream.on('end', function () {
        console.log("End stream for", "test2.jpg")
    });
})();
```

And here, the corresponding output:
```
Write chunk for test1.jpg
Write chunk for test2.jpg
Write chunk for test2.jpg
End stream for test2.jpg
Write chunk for test1.jpg
End stream for test1.jpg
```

Where I was expecting something like that:
```
Write chunk for test1.jpg
Write chunk for test1.jpg
End stream for test1.jpg
Write chunk for test2.jpg
Write chunk for test2.jpg
End stream for test2.jpg
```

I'm very interested to know whether you are able to reproduce this behavioror have any hint on what i could do wrong. Thank you for your time and for the great work you're doing, this module is really cool !

**Comment by mitar** [comment] 2016-03-07 12:12
@Etsitpab, please open a new ticket and put all this information there.

**Comment by LinusU** [comment] 2016-03-07 12:19
Output for me:

```text
Write chunk for test1.jpg
Write chunk for test1.jpg
End stream for test1.jpg
Write chunk for test2.jpg
Write chunk for test2.jpg
End stream for test2.jpg
```

**Comment by Etsitpab** [comment] 2016-03-07 12:23
Well, I don't know why it doesn't work. Looks like we are stuck.
I'm using Debian sid by the way but I have another laptop under Ubuntu. I
will try as soon as possible if I also have this problem with it.

Thank you very much.
Baptiste

2016-03-07 13:19 GMT+01:00 Linus Unnebäck <notifications@github.com>:

**Comment by LinusU** [comment] 2016-03-07 12:33
I'm using OS X without pango installed...

**Comment by Etsitpab** [comment] 2016-03-07 12:35
Ok, do you think that I could be related or that I should try something
like uninstalling pango ?

2016-03-07 13:33 GMT+01:00 Linus Unnebäck <notifications@github.com>:

**Comment by LinusU** [comment] 2016-03-07 12:35
Hmm, I don't *think* that it's related, but you never know :)

**Comment by Etsitpab** [comment] 2016-03-07 12:38
I tried to uninstall it, but I doesn't make any difference :-(

2016-03-07 13:35 GMT+01:00 Linus Unnebäck <notifications@github.com>:

**Comment by LinusU** [comment] 2016-03-07 12:41
Did you run `node-gyp rebuild` afterwards?

**Comment by Etsitpab** [comment] 2016-03-07 12:44
No, I have to get back to work, I will try it tonight. thank you very much
for your help !
Cheers,
Baptiste

2016-03-07 13:41 GMT+01:00 Linus Unnebäck <notifications@github.com>:

**Comment by LinusU** [comment] 2016-03-07 12:45
No problem :+1:
