### ISSUE TITLE
CAIRO_EXTEND_REFLECT when extending image

### ISSUE THREAD

**Issue by ddcovery** [Automattic/node-canvas#1249] opened 2018-09-19 17:17 UTC
In version 1.6.12, method drawImage extends the imge using CAIRO_EXTEND REFLECT:

> if (needsExtraSurface) {
>    ...
>    cairo_pattern_set_extend(cairo_get_source(ctxTemp), CAIRO_EXTEND_REFLECT);
>    cairo_paint_with_alpha(ctxTemp, 1);
>    surface = surfTemp;
>  }

Finally you perform the drawing using the default cairo_pattern_set_extend

> cairo_pattern_set_extend(cairo_get_source(ctx), CAIRO_EXTEND_NONE);

This "NONE" is doing nothing, because extend ALLWAYS uses the surfTemp version that contains a CAIRO_EXTEND_REFLECT and final result is a REFLECT extend.

This changes de default drawImage behaviour that is CAIRO_EXTEND_NONE (similar to Firefox/Chrome/...).

Actually, I solve this problem cleaning the reflected areas with extra code... problem is when the canvas where I paint the image contains useful contents  this extra content is overpainted with the reflect.

**Comment by ddcovery** [comment] 2018-09-20 08:46
Ok, sorry.

I have 2 images:

* images/small.jpg, 801x1200
  ![small](https://user-images.githubusercontent.com/6564217/45802984-9daa7b00-bcb8-11e8-98ec-c644e0aff2c9.jpg)

* image/big.jpg 2400x1602
  ![big](https://user-images.githubusercontent.com/6564217/45802991-a13e0200-bcb8-11e8-92ed-dc6d527a8c78.jpg)

This code loads the two images and draws the small one over the big one forcing extend:

```javascript
const Canvas = require("canvas");
const Image = Canvas.Image;
const fs = require("fs");
const Q = require("bluebird");

// Draw cat with lime helmet
loadImage(__dirname + '/images/small.jpg').then(smallImg => loadImage('images/big.jpg').then(bigImg => {

  console.log("smallImg:", smallImg.width, smallImg.height); // 801 1200
  console.log("bigImg:", bigImg.width, bigImg.height); // 2400 1602
  
  var canvas = new Canvas(bigImg.width, bigImg.height);
  const ctx = canvas.getContext('2d');
  ctx.drawImage(bigImg, 0, 0);
  //return saveCanvas(canvas, __dirname + "/1.png");
  ctx.drawImage(smallImg, -800, -200, canvas.width, canvas.height, 0, 0, canvas.width, canvas.height);
  return saveCanvas(canvas, __dirname + "/result.png");

}));


function loadImage(src) {
  return new Q((resolve, reject) => {
    fs.readFile(src, function (err, squid) {
      if (err) {
        reject(err);
      } else {
        img = new Image;
        img.src = squid;
        resolve(img);
      }
    });
  });

}

function saveCanvas(canvas, dst) {
  return new Q((resolve, reject) => {

    const
      out = fs.createWriteStream(dst)
      , stream = canvas.pngStream();

    stream.on('data', function (chunk) {
      out.write(chunk);
    });

    stream.on('end', function () {
      console.log('saved png');
      resolve();
    });
  });
}
```

This is the result with  1.6.9:

  ![result](https://user-images.githubusercontent.com/6564217/45806700-04806200-bcc2-11e8-94fd-b79643da5150.png)

And this with 1.6.12:
 ![result](https://user-images.githubusercontent.com/6564217/45806839-54f7bf80-bcc2-11e8-8388-9bdccdc690cf.png)

**Comment by chearon** [comment] 2018-09-20 13:12
Well that's not good. Neither of those look correct against the code though, shouldn't the small image be scaled? Since for `ctx.drawImage(smallImg)`, `dWidth` and `dHeight` are bigger than the small image's width and height.

**Comment by ddcovery** [comment] 2018-09-20 14:03
version 1.6.9 behaviour is similar to that of Firefox,Chrome,Edge browsers.

You can try it:  http://plnkr.co/edit/qw7czf?p=info

**Comment by ddcovery** [comment] 2018-09-20 15:48
As I understand, nothing has to be scaled because `sw==dw` and `sh==dh`.

Extend is applied because source limits `(sx, sy, sw, sh)` are out of `smallImg` bounds `(0, 0, smallImg.width,  smallImg.height)` and you require a way to "paint" pixels that are out of the souce image.

The default way to extend the source image to source limits is CAIRO_EXTEND_NONE (do nothing) that is  the way Firefox, Chrome, Edge paint too

1.6.9 version is working properly.

**Comment by zbjornson** [comment] 2018-09-20 15:56
Thanks for the info.

@asturur this is probably from #1229/#1243 (in 1.x and 2.x)

**Comment by zbjornson** [comment] 2018-09-22 19:12
@asturur do you have time to look at this regression by chance?

**Comment by asturur** [comment] 2018-09-22 19:53
i have to because this is why maybe global composite operation still fail me sometimes.
Thanks for the lead.

**Comment by asturur** [comment] 2018-09-22 19:56
My first question is we should have tests catching this?

**Comment by asturur** [comment] 2018-09-22 20:04
ok i understand....
So the extend reflect is there because otherwise the test that stitch together big small pieces of the big jpeg have some kinds of lines on the border.

I think i can fix it removing the extend, and figuring out a way to make the lines of stitching disapper ( maybe some rounding of pixels or applying the clipPath on the temporary surface.

I have also to verify how this code should behave on the browser because i have no idea now.

I need some days because i m travelling tomorrow, but maybe i can look at it.

I won't let the bug to rot, promise.

**Comment by asturur** [comment] 2018-09-23 07:27
https://github.com/Automattic/node-canvas/pull/1251

Have a look at the PR.

**Comment by zbjornson** [comment] 2018-10-09 19:01
Fixed in #1251 (v2.x) and a0af588 (v1.x).

**Closed by zbjornson** 2018-10-09 19:01 UTC
Labels: Bug

**Comment by LinusU** [comment] 2018-10-10 06:28
Released as:

- `canvas@2.0.0-alpha.18`
- `canvas@1.6.13`

**Comment by bennlich** [comment] 2018-12-21 18:50
It looks like this is still a bug for some usages of `drawImage`. See https://github.com/Automattic/node-canvas/pull/1335.

**Comment by asturur** [comment] 2018-12-21 19:57
removing the reflect creates thin gaps in tiling sometimes. That is the reason why it has been kept

**Comment by bennlich** [comment] 2018-12-22 02:36
Ah, k. From your comment above, I thought you might have been considering some other solutions to the tiling gaps. At first glance, the reflect solution seems a little heavy-handed / like it's causing some extra code complexity and side-effects. Are the tile gaps ever larger than 1px?

In any case, I will assume you've thought about this way more than me :)

**Comment by asturur** [comment] 2018-12-22 07:31
from what i understood reflect fills the gap that are aliasing effect of rounding when there is scaling. Always under 1px.

Much code complexity has been added in that area by me, in order to support globalCompositeOperation on the drawImage 9 arguments versions.
