### ISSUE TITLE
Unsupported image type for .webp format

### ISSUE THREAD

**Issue by flameface** [Automattic/node-canvas#2279] opened 2023-08-28 04:51 UTC
## Issue

```js
const canvas = require('canvas');
// code.....

canvas.loadImage("https://i.ytimg.com/vi_webp/mpWnhkMLIu4/maxresdefault.webp");
```

```
Error: Unsupported image type
```

All `.webp` images doesn't load, 

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.11.2
* Environment (node 20.3.0 on Windows 10 22H2):

**Comment by UnschooledGamer** [comment] 2023-08-29 04:08
> ## Issue
> ```js
> const canvas = require('canvas');
> // code.....
> 
> canvas.loadImage("https://i.ytimg.com/vi_webp/mpWnhkMLIu4/maxresdefault.webp");
> ```
> 
> ```
> Error: Unsupported image type
> ```
> 
> All `.webp` images doesn't load,
> 
> ## Your Environment
> * Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): canvas@2.11.2
> * Environment (node 20.3.0 on Windows 10 22H2):

node-canvas doesn't have support for .webp image types up till now. Users are asking for it's support since 2015. 

You can try adding the decoding support by using web assembly 💀 . 
There are some npm packages for node-canvas but I haven't tried them.

Refs: https://github.com/Automattic/node-canvas/issues/562 https://github.com/Automattic/node-canvas/issues/1258

**Comment by samon12321** [comment] 2023-09-07 09:15
any solution ?

**Comment by flam3face** [comment] 2023-09-07 11:54
@samon12321 use `@napi-rs/canvas`

**Comment by LinusU** [comment] 2023-10-02 10:27
Duplicate of #1258, where a workaround using `@cwasm/webp` is shared

**Closed by LinusU** 2023-10-02 10:27 UTC
