### ISSUE TITLE
The specified procedure could not be found

### ISSUE THREAD

**Issue by EvaisaGiac** [Automattic/node-canvas#1219] opened 2018-08-08 04:44 UTC
I get this error and I've seen a few old issues that have it but I can't seem to figure out how to fix it.

Error: The specified procedure could not be found.
\\?\E:\Deep Doodle\node_modules\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (module.js:653:18)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Deep Doodle\node_modules\canvas\lib\bindings.js:3:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
make: *** [server] Fout 1

**Comment by zbjornson** [comment] 2018-08-08 05:17
I think this can happen for a few reasons: (a) if you have another module that depends on one of the same dependencies of canvas, like cairo, (b) if you have multiple versions of canvas loaded by the same node.js process, sometimes, (c) if canvas was built with a different version of the dependencies than it's attempting to run with. When Windows searches for a DLL, if it finds one already loaded in memory with the same name, that one will be used even if it's the wrong one.

Try deleting your node_modules folder and re-installing, or see if you have multiple modules being loaded that depend on cairo, or multiple version of canvas... If you're up for it, you can follow these instructions to enable logging of DLL loading: https://ofekshilon.com/2013/06/22/entry-point-not-found-and-other-dll-loading-problems/

**Comment by EvaisaGiac** [comment] 2018-08-08 05:57
Eh I think I am too stupid to figure out how to enable logging but I removed node modules and it still gives the same error
The only other thing depending on cairo is sharp

**Comment by zbjornson** [comment] 2018-08-08 06:07
If you have Sharp also, then then this is a dupe of #930. There's some useful info in that ticket. I haven't gotten back to trying to figure out DLL redirection, but I think the Sharp maintainers made a possible fix. Feel free to post in #930...

**Closed by zbjornson** 2018-08-08 06:07 UTC

**Comment by OFFSETSYNT4X** [comment] 2023-03-24 02:07
Loading canvas after other modules that depends on one of the same dependencies of canvas resolved my issue. Worth a shot right?

**Comment by Shubhamrawat5** [comment] 2023-05-10 06:02
Getting same error

**Comment by elhadjx** [comment] 2025-02-20 13:42
I'm too getting the same error. what is this !!!
