### ISSUE TITLE
Unable to use canvas from another module in drawImage()

### ISSUE THREAD

**Issue by rogerz** [Automattic/node-canvas#559] opened 2015-05-19 15:54 UTC
I have two modules using `node-canvas` and I want to import the content of canvas in module 1 into the canvas of module 2. But an exception `TypeError: Image or Canvas expected` is raised when `drawImage()` is used for this purpose.

The problem can be reproduced in two simple modules
## m1-canvas

```
var Canvas = require('canvas');

module.exports = new Canvas();
```
## m2-canvas

```
m1 = require('m1-canvas');
var Canvas = require('canvas');

var m2 = new Canvas();
var m3 = new Canvas();

var ctx = m2.getContext('2d');

ctx.drawImage(m3, 0, 0, m3.width, m3.height);

ctx.drawImage(m1, 0, 0, m1.width, m1.height);

module.exports = {};
```

Error message when running m2

```
ctx.drawImage(m1, 0, 0, m1.width, m1.height);
    ^
TypeError: Image or Canvas expected
    at Object.<anonymous> (/Users/zhangyujun/Workspace/m2-canvas/index.js:11:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

**Comment by GabiThume** [comment] 2015-08-06 02:47
https://github.com/Automattic/node-canvas/issues/487 suggests a possible temporary fix for that (i.e. requiring the same canvas module in both cases). Maybe it can helps.

**Comment by buenjybar** [comment] 2015-12-15 20:00
have you tried the previous solution #487 ? 

it seems that i have the same issue using 'jsdom' module.

every time i create a new canvas HTMLElement, render shapes in, export it to image, and decide to draw it to an other canvas HTMLElement it will throw that exception.

**Comment by zbjornson** [comment] 2018-07-02 02:32
Duplicate of #487.

**Closed by zbjornson** 2018-07-02 02:32 UTC
