### ISSUE TITLE
rotation made by default when I load an image

### ISSUE THREAD

**Issue by sami93** [Automattic/node-canvas#1984] opened 2022-02-08 09:18 UTC
## Bug
I have a problem when I load some images uploaded from mobile device and when I load image with canvas I have the image that is made with rotation by default (while I have verified that there is no rotation in the original image)

## Steps to Reproduce

```js
import { createCanvas, loadImage } from 'canvas';
const img = await loadImage(pictureBuffer)
const canvas = createCanvas(img.width, img.height, 'pdf');
const ctx = canvas.getContext('2d')
ctx.drawImage(img, 0, 0, img.width, img.height)
const pdfBuffer = canvas.toBuffer('application/pdf');
// save pdf
```

## Your Environment
* Version of node-canvas: 2.9.0
* node v14.15.3 on Mac OS X 12.2

**Comment by LinusU** [comment] 2022-02-08 10:53
Seems like a duplicate of #1670?

**Comment by zbjornson** [comment] 2022-02-26 04:39
@sami93 please read through #1670, and if that doesn't seem to be a duplicate, I'll reopen this.

**Closed by zbjornson** 2022-02-26 04:39 UTC
