### ISSUE TITLE
Build error with SVG support

### ISSUE THREAD

**Issue by Khorynthium** [Automattic/node-canvas#1205] opened 2018-07-17 13:07 UTC
Cannot build package with svg support. It fails on a link stage because of missing `error` method in Image class.
https://github.com/Automattic/node-canvas/blob/master/src/Image.cc#L395
Here this method is getting called but looks like It's implementation has been removed by this commit https://github.com/Automattic/node-canvas/commit/1f4b646b9108542be9d6a984bd08eed0577f1cdf in couple of months after SVG PR got merged.

**Comment by zbjornson** [comment] 2018-07-17 16:07
Dupe of #1123. Will try to fix this week (also happy to review a PR if you or anyone else wants to take a stab at it). Thanks for finding that commit.

**Closed** 2018-07-17 16:07 UTC
Labels: Duplicate
