### ISSUE TITLE
[typescript] wrong types on getContext()

### ISSUE THREAD

**Issue by doritosxxx** [Automattic/node-canvas#1783] opened 2021-04-14 09:09 UTC
### [Possibly part of #1656](https://github.com/Automattic/node-canvas/issues/1656#issue-686323296)

**getContext()** returns type NodeCanvasRenderingContext2D. NodeCanvasRenderingContext2D extends CanvasRenderingContext2D, which has the **canvas** field.

**canvas** field has type HTMLCanvasElement. But as far as i know this library doesn't work with DOM. Furthermore HTMLCanvasElement can't be explicitly converted to Canvas.

## Steps to Reproduce

```ts
import { Canvas } from 'canvas'

const canvas = new Canvas(100, 100)
const ctx = canvas.getContext("2d")

// cts.canvas is HTMLCanvasElement accoring to typings.
// but it should be Canvas.
// HTMLCanvasElement has the "toBlob" method

// TypeError: ctx.canvas.toBlob is not a function
ctx.canvas.toBlob(()=>{})

// This one won't compile.
ctx.canvas.toBuffer()

// This one works fine.
;(ctx.canvas as unknown as Canvas).toBuffer()
```

## Your Environment
* canvas@2.7.0
* typescript@4.2.4
* node v14.15.4 on Windows10 20H2

**Comment by zbjornson** [comment] 2021-04-20 05:05
Yeah, for the sake of simplicity I had just extended `CanvasRenderingContext2D`, but as you found in #1656, that turned out to be problematic.

Happy to review a PR if you want to work on this. Meanwhile I'm going to close this as a duplicate of #1656.

**Closed by zbjornson** 2021-04-20 05:05 UTC
