### ISSUE TITLE
We need `fontBoundingBoxAscent` in ctx

### ISSUE THREAD

**Issue by huankong233** [Automattic/node-canvas#2321] opened 2023-12-06 14:24 UTC
## Issue or Feature
Can't give the `fontBoundingBoxAscent` value

## Steps to Reproduce
```js
import { createCanvas } from 'canvas'
var canvas = createCanvas(200, 200);
var ctx = canvas.getContext('2d');
const text = ctx.measureText("huan")
console.log(text)
```
console:
``` js
{
  width: 209.548828125,
  actualBoundingBoxLeft: 3,
  actualBoundingBoxRight: 206.61328125,
  actualBoundingBoxAscent: 62,
  actualBoundingBoxDescent: 20,
  emHeightAscent: 90,
  emHeightDescent: 24,
  alphabeticBaseline: -0
}
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): 2.11.2
* Environment (e.g. node 20.9.0 on macOS 14.1.1): node18 on windows 10

**Comment by stefcameron** [comment] 2024-02-03 18:28
Similar/duplicate of #1940

**Closed** 2024-02-05 20:32 UTC
Labels: Text & Fonts, Help wanted, Feature
