### ISSUE TITLE
ctx.filter

### ISSUE THREAD

**Issue by CarlosUvaSilva** [Automattic/node-canvas#1373] opened 2019-02-20 16:30 UTC
Is  `ctx.filter` implemented?

I saw this issue (https://github.com/Automattic/node-canvas/issues/1063) but I didn't understand if it ended up being implemented or not?

```
    const canvas = createCanvas(image.width,image.height)
    const ctx = canvas.getContext('2d')

    ctx.drawImage(image, 0, 0)
    ctx.filter = 'grayscale(100%)'
```
I'm trying to do it and I can't, I'm assuming it's not implemented ?

Thank you

**Comment by zbjornson** [comment] 2019-02-20 16:34
It's not implemented yet, no. Before canvas v2, there was a `ctx.filter` property, but it was not the same as the HTML standard `ctx.filter`, so in v2 we renamed the non-standard property to avoid the mismatch.

**Comment by CarlosUvaSilva** [comment] 2019-02-20 16:34
hello @zbjornson, thanks for the prompt reply

Is there any legacy/non-standard way to do this?

**Comment by zbjornson** [comment] 2019-02-20 16:52
I think the only way is by manipulating the pixel data. For `grayscale(100%)` that'd be something like this:

```js
const {Image, createCanvas} = require("canvas");
const fs = require("fs");

const width = 276, height = 183;
const img = new Image();
img.src = "https://mdn.mozillademos.org/files/3716/Test_Form_5.jpeg";
img.onload = () => {
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext("2d");
  ctx.drawImage(img, 0, 0);
  const id = ctx.getImageData(0, 0, width, height);
  ctx.clearRect(0, 0, width, height);
  const data = id.data;
  for (let i = 0; i < data.length; i += 4) {
	let r = data[i];
	let g = data[i + 1];
	let b = data[i + 2];
	let y = 0.299 * r + 0.587 * g + 0.114 * b;
	data[i] = y;
	data[i + 1] = y;
	data[i + 2] = y;
  }
  ctx.putImageData(id, 0, 0);
  fs.writeFileSync("grayscale.png", canvas.toBuffer());
};
img.onerror = err => console.log(err);
```

**Comment by CarlosUvaSilva** [comment] 2019-02-20 17:11
@zbjornson thanks! works perfectly

**Comment by LinusU** [comment] 2019-02-23 08:38
@CarlosUvaSilva https://stackoverflow.com/a/596243/148072

**Comment by zbjornson** [comment] 2019-02-23 09:24
Oops, I missed your edit, didn't mean to ignore you. Thanks for linking that Linus.

**Comment by Aci-yt** [comment] 2022-08-10 17:54
Is this implemented now? The issue is closed, but it doesn't seem to be functional

**Comment by zbjornson** [comment] 2022-08-10 18:01
It's tracked in #1063, which I just realized was closed incorrectly. I don't have any work in progress on it though.

**Closed by zbjornson** 2022-08-10 18:01 UTC
