### ISSUE TITLE
Help us test the 2.0 alpha

### ISSUE THREAD

**Issue by LinusU** [Automattic/node-canvas#916] opened 2017-05-03 22:08 UTC
Just released the long overdue first alpha of the 2.x branch, `canvas@2.0.0-alpha.1`. Please help me test it 🎉 

To install it, run `npm install canvas@next`

**Comment by zbjornson** [comment] 2017-05-04 17:30
One regression found and fixed in #917.

**Comment by zbjornson** [comment] 2017-05-05 19:08
One more bug: https://github.com/Automattic/node-canvas/commit/8b5dc056b3045ffe6665c38c732dc7b37ce7c454#commitcomment-22033227

**Comment by asturur** [comment] 2017-05-14 20:23
Hello! i would love to help testing it.
I really need to align fabricjs in browser and nodejs.
What is the situation with custom font? what libraries are necessary/suggested?

Any compiled version from @chearon ?

**Comment by chearon** [comment] 2017-05-16 18:48
@asturur Planning on it! I'll report back here when I get the time to do it

**Comment by chearon** [comment] 2017-05-16 18:50
> What is the situation with custom font? what libraries are necessary/suggested?

Custom fonts API has changed (see readme) and Pango is now a hard requirement

**Comment by azangru** [comment] 2017-06-06 19:19
@LinusU I've stumbled across what seems like a memory leak in the the 2.0 alpha (at least, it is absent in the 1.x branch). I have submitted an [issue](https://github.com/Automattic/node-canvas/issues/922) with a [basic repro case](https://github.com/azangru/node-canvas-testing).

**Comment by chearon** [comment] 2017-07-09 12:36
Hey everyone, I've just released canvas-prebuilt for versions `v2.0.0-alpha.1` and`v2.0.0-alpha.2`

**Comment by jhsware** [comment] 2017-07-11 06:36
@chearon Regarding custom fonts, you mentioned to read the readme, but I have looked at the example project and README.md. They all refer to registerFont (which I have used successfully), but node-canvas doesn't appear to expose that method anymore. Where can I read about how to load custom fonts?

**Comment by zbjornson** [comment] 2017-07-11 06:38
@jhsware I think that also got hidden by mistake; see this: https://github.com/Automattic/node-canvas/pull/929#issuecomment-314305548

**Comment by LinusU** [comment] 2017-07-11 07:07
Whoops, that's probably my fault 🙈 will fix

**Comment by jhsware** [comment] 2017-07-11 07:09
@LinusU looking forward to that! If you fix it I'll see if I can add a test for custom fonts... since I need it to work :D

**Comment by LinusU** [comment] 2017-07-11 07:11
You should be able to use `v2.0.0-alpha.2` (`npm install canvas@v2.0.0-alpha.2`) for now, that one shouldn't have that problem :)

**Comment by LinusU** [comment] 2017-08-28 09:56
Fixed in `v2.0.0-alpha.3` 🎉

**Closed** 2018-10-14 12:58 UTC
