### ISSUE TITLE
Register font with raw Buffer or Uint8Array

### ISSUE THREAD

**Issue by leo91000** [Automattic/node-canvas#2202] opened 2023-02-25 16:26 UTC
Hello,

Is it possible to register font using raw buffer or uint8array instead of filepath ?

Thanks !

**Comment by chearon** [comment] 2023-02-25 20:44
Not yet, because the available APIs don’t give us that ability. When Pango 2 is released I’ll see if we can add that.

**Comment by zbjornson** [comment] 2023-12-28 22:36
Duplicate of #386.

**Closed by zbjornson** 2023-12-28 22:36 UTC
