### ISSUE TITLE
ctx.font does not use the font weight part

### ISSUE THREAD

**Issue by Jack-Works** [Automattic/node-canvas#846] opened 2016-11-18 16:07 UTC
'bold 20px sans-serif' and '100 20px sans-serif' is the same weight
(And I also tried other fonts)

**Comment by chearon** [comment] 2016-11-18 16:20
can you include the stuff listed in the issue template [here](https://github.com/Automattic/node-canvas/blob/master/.github/ISSUE_TEMPLATE.md)? do you know if you are using Pango or not?

**Comment by Jack-Works** [comment] 2016-11-18 16:30
Um... Sorry, I will try to minimize the problem code later, now I am away from pc
Environment: Windows 10, Node 6.
Code:
ctx.font = 'bold 20px sans-serif'

**Comment by Jack-Works** [comment] 2016-11-19 15:40
Um sorry, I make a reproduce now.

Node-canvas seemed to be not recognize the value
lighter, bolder, 100, 200, 300, 400, 500, 600, 700, 800, 900
but it DOES, read 'bold'

On mdn.io/fontWeight , I found that these unsupported value is "Relative to the parent", and on browser(these values work)

Node-canvas
![image](https://cloud.githubusercontent.com/assets/5390719/20456410/35707fa6-aeb1-11e6-8240-e3cdcaf66338.png)

Browser
![image](https://cloud.githubusercontent.com/assets/5390719/20456415/517feb14-aeb1-11e6-9bc2-368c4cd7e2ba.png)

Code:

> `var Canvas = require('canvas')
var canvas = new Canvas(1400, 900)
var ctx = canvas.getContext('2d')
ctx.font = '40px "Microsoft Yahei"'
ctx.fillText('ABC', 40, 180)
ctx.font = 'lighter 40px "Microsoft Yahei"'
ctx.fillText('ABC', 370, 180)
require('fs').writeFileSync('out.png', canvas.toBuffer())`

(on the browser is quite similar)

**Comment by Jack-Works** [comment] 2016-12-12 13:21
@chearon Um... Hello? I'm done for the re-preduce step, is it a Pango problem? Thanks

**Comment by chearon** [comment] 2016-12-12 13:44
Oh it's probably because you are using `lighter`. You can't do that since there is no initial font weight for that to be relative to. Try `light`

**Comment by Jack-Works** [comment] 2016-12-12 13:49
Um... Than what about values like 100 200 300 400? They doesn't work
either...

**Comment by chearon** [comment] 2016-12-12 14:23
Sorry about that, I should have read your whole comment. Yeah, I'm seeing the same thing. It doesn't look like any weights are working for any fonts on Windows. Try also `900 Arial` vs `100 Arial`.

You might have to wait until version 2 is released which does force Pango on Windows. It has good support for font selection so I'm pretty sure that would fix it but don't have time to test it right now

**Comment by Jack-Works** [comment] 2016-12-12 14:25
Cool, thanks!

**Comment by zbjornson** [comment] 2018-11-10 02:28
Just tested and confirmed this is fixed in 2.x!

**Closed by zbjornson** 2018-11-10 02:28 UTC
Labels: Fixed?, Text & Fonts
