### ISSUE TITLE
Canvas latest version not building

### ISSUE THREAD

**Issue by sachin-agarwal-by** [Automattic/node-canvas#1760] opened 2021-03-04 04:34 UTC
I have installed latest version of canvas 2.7.0 (same error for 2.6.1 version also)and its showing error while installing package.

![image](https://user-images.githubusercontent.com/69183793/109911888-fb887d00-7cd0-11eb-956e-22257bb9ab1f.png)

**Comment by zbjornson** [comment] 2021-03-30 04:07
`unable to get local issuer certificate` can mean your certificate authority bundle used by Python is old or missing certs for GitHub. These StackOverflow answers might help:

https://stackoverflow.com/questions/51925384/unable-to-get-local-issuer-certificate-when-using-requests-in-python
https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

This is not really an issue with node-canvas and not an issue I can provide much help.

**Comment by zbjornson** [comment] 2021-03-30 04:24
Closing as a duplicate of #1759. That issue has the error message in the issue body so can be found more easily when searching.

**Closed by zbjornson** 2021-03-30 04:24 UTC
Labels: Installation help, Needs more info
