### ISSUE TITLE
Can't install cairo using wget on MacOSX - can't install canvas

### ISSUE THREAD

**Issue by kristianmandrup** [Automattic/node-canvas#603] opened 2015-07-31 23:46 UTC
At the end of the cairo `wget` install, I get:

```sh
... removing cairo-1.12.16
$
```

Also tried `brew install cairo` with the same end result as shown below

I've also tried 

```sh
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/opt/X11/lib/pkgconfig
npm install canvas
```

as mentioned in #528. Any suggestions? Thanks :)

Even calling `npm install LinusU/node-canvas#pangocairo-test` fails with the same error. Is it a basic network/http error?! :O 

```sh
... removing cairo-1.12.16
✔ ~/repos/aurelia-projects/my-app 
01:37 $ npm install canvas
\
> canvas@1.2.7 install /Users/kristianmandrup/repos/aurelia-projects/my-app/node_modules/canvas
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response dowloading http://nodejs.org/dist/v2.3.4/node-v2.3.4.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Users/kristianmandrup/npm/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/kristianmandrup/npm/lib/node_modules/npm/node_modules/request/request.js:985:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:415:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:305:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "/usr/local/bin/iojs" "/Users/kristianmandrup/npm/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kristianmandrup/repos/aurelia-projects/my-app/node_modules/canvas
gyp ERR! node -v v2.3.4
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/iojs" "/Users/kristianmandrup/npm/bin/npm" "install" "canvas"
npm ERR! node v2.3.4
npm ERR! npm  v2.13.0
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.2.7 install script 'node-gyp rebuild'.
...
```

**Comment by LinusU** [comment] 2015-08-01 16:26
The problem is that you are using iojs with a version of npm that is for Node.js.

I'm not sure how to resolve it but I would search the npm repos issues for a solution, or post a bug there.

I'm closing this since you problem is not something that we can do anything about, and it's not specific to this package.

**Closed by LinusU** 2015-08-01 16:26 UTC

**Comment by kristianmandrup** [comment] 2015-08-01 16:39
I was only installing this in order to get `nib` for Stylus working, since canvas seemed to be a requirement.

"Node canvas is a Cairo backed Canvas implementation for NodeJS."

Why would it be a problem that I:  "iojs with a version of npm that is for Node.js" since node-canvas is obviously canvas for node!? Lost in translation...

**Comment by LinusU** [comment] 2015-08-01 16:48
You are using iojs, but your build tool is configured for Node.js.

The build tool tries to get the source for your version of iojs by fetching `http://nodejs.org/dist/v2.3.4/node-v2.3.4.tar.gz`, but that doesn't work since that's nodejs website.

Here is an issue discussing this: nodejs/io.js#433

**Comment by LinusU** [comment] 2015-08-01 16:50
This could probably fix your error: https://github.com/mafintosh/node-gyp-install

**Comment by kristianmandrup** [comment] 2015-08-01 17:28
Ah, this is sooo awesome!!! I've had loads of problems related to iojs and the errors mentioning node-gyp. This finally sheds some light... Thanks :)

**Comment by LinusU** [comment] 2015-08-01 17:32
No problem, happy hacking :+1:
