### ISSUE TITLE
Error: Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by gilles-hemmerle** [Automattic/node-canvas#2135] opened 2022-10-12 10:26 UTC
## Issue

I have a project (nestjs) which works perfectly with canvas
I added nest-commander (which allows to create a cli command for my nest application).

When running the following command, the script fails:

**Command:**
```
npx ts-node src/commands.ts
```

**Error:**
```
Error: Cannot find module '../build/Release/canvas.node'
Require stack:
- /home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/node_modules/canvas/lib/bindings.js
- /home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/node_modules/canvas/lib/canvas.js
- /home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/node_modules/canvas/index.js
- /home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/src/files/files.service.ts
- /home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/src/tulips/tulips.controller.ts
- /home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/src/tulips/tulips.module.ts
- /home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/src/app.module.ts
- /home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/src/commands.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .js] (/home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/node_modules/ts-node/src/index.ts:1587:43)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/node_modules/canvas/lib/bindings.js',
    '/home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/node_modules/canvas/lib/canvas.js',
    '/home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/node_modules/canvas/index.js',
    '/home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/src/files/files.service.ts',
    '/home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/src/tulips/tulips.controller.ts',
    '/home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/src/tulips/tulips.module.ts',
    '/home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/src/app.module.ts',
    '/home/gillesh/Documents/development/projects.iabsis.com/tulip/tulip-api/src/commands.ts'
  ]
}
```

tsconfig.json file:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
    "resolveJsonModule": true,
    "esModuleInterop": true
  }
}
```

It seems that when building with ts-node, it is unable to find the file  '../build/Release/canvas.node' for any reason.
If i remove the `import { Canvas, Image } from 'canvas';` line, script build with all other npm dependencies working.

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): **canvas@2.9.3**
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): **node 14.18.1 / npm 8.1.0**

**Comment by arbassic** [comment] 2022-10-17 12:46
Related to:

https://github.com/Automattic/node-canvas/issues/1221

for me reinstallation helped, even if it is a sub-dependency

```sh
yarn add -D canvas
```

**Comment by gigamesh** [comment] 2022-10-20 12:00
I think I've tried every suggestion in every thread on the internet about this issue but its still happening. I'm using pnpm, and the error happens when trying to run tests with vitest.

**Comment by zbjornson** [comment] 2022-10-30 04:21
There's not enough info in the log to troubleshoot. What's your `npm install canvas` output, and what happens if you use `node` instead of `npx ts-node`?

**Comment by gigamesh** [comment] 2022-10-30 18:58
I ended up getting around the problem by just replacing `getContext` with a no-op (using vitest):

```
  HTMLCanvasElement.prototype.getContext = vi.fn();
```

**Comment by RUSHt** [comment] 2022-11-02 11:33
I was having similar issues with 

```
'.../canvas' is not supported resolving ES modules
``` 
and 
```
Cannot find module '.../canvas.node'
```

So...

```
import { createCanvas, loadImage, Image } from "canvas";
```
Was replaced with...
```
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const { createCanvas, loadImage, Image } = require('canvas');
```
My dev environment (macOS) worked fine with the initial import statement, but production (AWS Linux) failed with the Can't find / not supporting ES5 modules errors.

**Comment by HitkoDev** [comment] 2023-01-23 13:06
This has been going on for ages. The problem is that whenever a matching version of a dependency is found to be already installed (based on lockfile and contents of `node_modules`), no `install` script is triggered for that dependency. One solution is to run `cd ./node_modules/canvas && npx node-pre-gyp install --fallback-to-build --update-binary` or `npm rebuild` after installing new dependencies.

However, I have several dependencies that need to install binaries the same way, and I've only been noticing this problem for canvas, so there might be something else going on with the way canvas handles it.

**Comment by lxfu1** [comment] 2023-02-27 12:16
**.npmrc**
```ts
public-hoist-pattern[]=canvas
```

**Comment by benstahl** [comment] 2023-03-23 06:51
I had this issue trying to use node-canvas via pnpm. What works was to delete the node_modules folder and re-install the reps with `pnpm install`

**Comment by wannabehero** [comment] 2023-04-23 17:13
I had `npm install --ignore-scripts` in my Dockerfile. Removing `--ignore-scripts` solved the issue.

**Comment by vtereshyn** [comment] 2023-12-15 09:43
Still issue. Here is reproduction repository - https://github.com/vtereshyn/pnpm-jest-jsdom-canvas

It fails all my tests

**Comment by vtereshyn** [comment] 2023-12-15 13:46
Not sure which side this issue should be fixed on, but I created similar in the PNPM repo - https://github.com/pnpm/pnpm/issues/7425

**Comment by zbjornson** [comment] 2023-12-28 22:55
Recent versions of node-canvas include the `--update-binary` flag (#1982), which should fix this.

**Closed by zbjornson** 2023-12-28 22:55 UTC
Labels: Installation help, Needs more info

**Comment by vtereshyn** [comment] 2024-01-05 14:55
@zbjornson recent version was released in April 2023, but the issue popped up at the end of 2023 and the beginning of 2024. I assume, that fix doesn't work

**Comment by zbjornson** [comment] 2024-01-05 19:10
@vtereshyn I think your issue with pnpm is unrelated to the OP's issue. The comments in this issue are about a few different underlying problems, but `--update-binary` addresses the issue in https://github.com/Automattic/node-canvas/issues/2135#issuecomment-1400307682, which got the most upvotes.

**Comment by popovidis** [comment] 2024-01-08 10:41
> @vtereshyn I think your issue with pnpm is unrelated to the OP's issue. The comments in this issue are about a few different underlying problems, but `--update-binary` addresses the issue in [#2135 (comment)](https://github.com/Automattic/node-canvas/issues/2135#issuecomment-1400307682), which got the most upvotes.

tried to command with `--update-binary` and unfortunately it did not work.

**Comment by saddamhr** [comment] 2024-01-19 07:03
If you use Next.js or Next.js 14, you may need to add the following to your next.config.js:

```
module.exports = {
 webpack: (config) => {
   config.resolve.alias.canvas = false;

   return config;
 },
}
```
ref: https://www.npmjs.com/package/react-pdf
this is work for me

**Comment by borontion** [comment] 2024-02-13 19:07
I resolved this issue by explicitly including `canvas` as a dependency, deleting `node_modules` and then installing again.

I am on an apple arm chip and it seems that there is no pre-compiled release for macos arm, so I have to compile this during installation. So make sure the [compilation](https://github.com/Automattic/node-canvas?tab=readme-ov-file#compiling) requirement can be satisfied.

**Comment by joshuanapoli** [comment] 2024-02-20 00:23
Check carefully the install output. The package build may fail because of "Package pixman-1 was not found in the pkg-config search path.".  In this case, you need to install the dependency. See #1065

**Comment by Olalexy1** [comment] 2025-03-19 15:23
> If you use Next.js or Next.js 14, you may need to add the following to your next.config.js:
> 
> ```
> module.exports = {
>  webpack: (config) => {
>    config.resolve.alias.canvas = false;
> 
>    return config;
>  },
> }
> ```
> 
> ref: https://www.npmjs.com/package/react-pdf this is work for me

Thank you

**Comment by dep** [comment] 2025-07-16 14:37
Update! For me, I had to switch to `vitest` to resolve this.

<img width="958" height="1067" alt="Image" src="https://github.com/user-attachments/assets/99ba97e0-e60e-407b-9322-ed8617c92cec" />

`packages/ui/vitest.config.js`

```js
import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import { resolve } from 'path'

export default defineConfig({
    plugins: [react()],
    resolve: {
        alias: {
            '@': resolve(__dirname, 'src')
        }
    },
    test: {
        globals: true,
        environment: 'jsdom',
        setupFiles: './src/setupTests.js',
        exclude: ['**/node_modules/**', '**/playwright/**']
    }
})
```

`packages/ui/src/setupTests.js`

```js
import '@testing-library/jest-dom'
```

**Comment by NathanD19** [comment] 2025-07-18 06:38
If you are using pnpm, run `pnpm approve-builds` and allow canvas build script

**Comment by vercamach** [comment] 2025-10-15 10:47
I still can't get it to work. 
macOS: Sequoia 15.6.1
node: 22.14
pnpm: 10.10.0

I installed all the necessary dependencies, tried to pnpm prune, pnpm rebuild, deleting node_modules and package.lock, restarting my computer, approve-builds and I still get the   Error: Cannot find module '../build/Release/canvas.node'
