### ISSUE TITLE
🚢 3.0.0 planning issue

### ISSUE THREAD

**Issue by LinusU** [Automattic/node-canvas#2232] opened 2023-04-19 06:43 UTC
Things to consider for the 3.0.0 major version:

- [x] Drop support for old Node.js versions (14.x EOL at 2023-04-30, 16.x EOL at [2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol/))
- [ ] Change the `Canvas` class to [`OffscreenCanvas`](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas)
    - [ ] Make our `OffscreenCanvas` extend [Node.js `EventTarget`](https://nodejs.org/api/events.html#eventtarget-and-event-api)
- [ ] Make `Image` and `ImageData` behave like browsers (using [node-gfx/image](https://github.com/node-gfx/image) & [node-gfx/image-data](https://github.com/node-gfx/image-data))
- [ ] Replace `simple-get` with [Node.js builtin `fetch`](https://nodejs.org/dist/latest-v20.x/docs/api/globals.html#fetch)
- [ ] Require [Pango 2](https://blogs.gnome.org/mclasen/2022/06/22/pango-1-90/) (if it's released in time)
    - [ ] New [`FontFace`](https://developer.mozilla.org/en-US/docs/Web/API/FontFace/FontFace) and [`document.fonts`](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet) based API instead of `registerFont`
    - [ ] Non-standard `fillGlyphs(face, glyphIds)` API for fast rendering if shaping has already been done (e.g. harfbuzzjs)

Please note that this issue is for discussing **breaking** changes and not a place for general feature requests!

**Comment by chearon** [comment] 2023-04-19 13:48
Added Pango 2, which will solve a ton of font issues.

Should N-API be considered a breaking change? I plan on testing a lot, but it will introduce at least a few regressions.

**Comment by LinusU** [comment] 2023-04-19 14:17
> Added Pango 2, which will solve a ton of font issues.

Nice! 🙌 

> Should N-API be considered a breaking change? I plan on testing a lot, but it will introduce at least a few regressions.

Might be a good idea 👍

**Comment by piranna** [comment] 2023-05-23 20:15
If we replace `Canvas` for `OffscreenCanvas`, can we get merged [my PRs](https://github.com/Automattic/node-canvas/pulls?q=is%3Aopen+is%3Apr+author%3A%40me+sort%3Aupdated-desc), specially https://github.com/Automattic/node-canvas/pull/1540 with the `ScreenBackend` class so we can have proper support for on-screen `Canvas`?

**Comment by jimmywarting** [comment] 2023-08-27 12:41
can we instead remove the hole `Image` and http stuff with a `createImageBitmap(blob)`?

**Comment by jimmywarting** [comment] 2023-08-27 12:42
why should OffscreenCanvas extend EventTarget?

**Comment by aoor9** [comment] 2023-11-24 23:11
Is `v3.0.0` released? Because it doesn't seem to be available on npm registry.

**Comment by LinusU** [comment] 2023-11-27 15:37
@zbjornson I saw that you pushed a v3.0.0 commit & tag to the repo, but we haven't published it to npm yet. The package.json still says that Node.js 10 is minimum version, and no other of the breaking changes are in yet.

Maybe we can add a few more breaking changes now before we re-tag and publish 3.0.0 to Npm? Or we consider 3.0.0 shipped and the breaking changes discussed above will go in 4.x...

I'll open some PRs which we could consider.

pinging @chearon also, do you have any input?

**Comment by LinusU** [comment] 2023-11-27 15:38
> why should OffscreenCanvas extend EventTarget?

According to MDN, `OffscreenCanvas` in the browser extends `EventTarget`? https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas

**Comment by chearon** [comment] 2023-11-27 16:51
It's not published to NPM because the Windows prebuilds aren't working (and neither @zbjornson or I have looked - that's always a huge time sink). `package.json` node got changed in #2235, so that technically is a breaking change.

**Comment by zbjornson** [comment] 2023-11-27 18:23
Specifically, the NAPI port means that prebuilds need to be reworked (https://github.com/Automattic/node-canvas/pull/2235#issuecomment-1747461108) and I haven't had time to do that.

In the meantime, I tried to make Node.js v21 prebuilds for the latest 2.x version, but those failed on Windows as Caleb said. https://github.com/Automattic/node-canvas/issues/2295#issuecomment-1783294105

As far as more changes, I favor deferring other changes to 4.x+ since the NAPI port unblocks using node-canvas in Bun and that work is done.

**Comment by LinusU** [comment] 2023-11-28 09:17
> As far as more changes, I favor deferring other changes to 4.x+ since the NAPI port unblocks using node-canvas in Bun and that work is done.

I'm all for releasing early! So I don't think we should block on anything else, but e.g. just bumping our minimum supported Node.js version (#2310) I think would be really nice to get in just so that we don't have to support old versions of Node.js that probably aren't used much, since they are end of life.

Are you two open on merging breaking changes until the prebuilds are fixed and we are ready to publish to npm? How do you feel about raising supported version as I did in #2310?

**Comment by zbjornson** [comment] 2023-11-28 22:25
> Are you two open on merging breaking changes until the prebuilds are fixed and we are ready to publish to npm?

Good with me as long as they don't make the current prebuild troubles worse :)

> How do you feel about raising supported version as I did in #2310?

👍

**Comment by LinusU** [comment] 2023-11-29 10:03
I've fixed the tests and increased the minimum version of Node.js.

Since the Node.js version is increased now, I don't think that #2309 is a breaking change anymore so no need to rush that.

Pango 2 doesn't seem to be released yet, so that change will not make it I guess.

I would have loved to land `Canvas` -> `OffscreenCanvas`, and the new `Image` & `ImageData`. But since that will probably affect the native code a bit it might make it harder to work on the prebuilds? And it might also take some time...

If I have time, I could implement those in a branch and then we could hold off on merging until prebuilds are done and we see that they work together...

-----

We also need to update the `v3.0.0` tag, which solution do you think would work best?

1️⃣ I move the [v3.0.0](https://github.com/Automattic/node-canvas/commit/a5b379bbc241d2731c2a4f8d4410f71f123dd1ee) commit using `git rebase` and then force push to `master`
2️⃣ We create a new empty commit that will be the tagged `v3.0.0` commit
3️⃣ We point the `v3.0.0` tag to whatever commit is the latest when we want to release v3.0.0 (probably ad793da)

If we don't think it will cause too many issues, I kind of prefer 1️⃣, just so that every release to npm matches up with a commit that bumps the version. This is probably something that should be enforced using [Npm package provenance](https://github.blog/2023-04-19-introducing-npm-package-provenance/) in the future...

**Comment by YuMuuu** [comment] 2024-01-03 05:47
The v3.0.0 release needs to merge #2309. When will you plan to merge it?

**Comment by quinton-ashley** [comment] 2024-01-27 15:33
Is v3 done yet?

**Comment by chearon** [comment] 2024-09-18 01:27
I was so happy to find out today that @zbjornson finished prebuilds (#2235) (it was a while ago, but I'm only recently carving out new free time...). I think that was the only blocker for 3.0.0? I don't think we're going to get any feedback on the alpha releases.

> Pango 2 doesn't seem to be released yet, so that change will not make it I guess.

I haven't seen any updates to the `pango2` branch in 2 years, so I've been slowly working on a new HarfBuzz-based font stack. It's a lot more work but at least we'll have the ability to fix more bugs people encounter (and it'll be very, very fast).

> We also need to update the `v3.0.0` tag, which solution do you think would work best?

Yeah, that messed up the changelog too. I like 1️⃣ as well, I just hope it doesn't cause too much trouble.

> This is probably something that should be enforced using [Npm package provenance](https://github.blog/2023-04-19-introducing-npm-package-provenance/) in the future...

`--provenance` looks like a great idea.

**Comment by zbjornson** [comment] 2024-09-23 21:50
@chearon https://github.com/Automattic/node-canvas/issues/2390 is the only regression I've seen in v3.0.0-pre.

**Comment by chearon** [comment] 2024-09-23 22:07
Oh yeah thanks, I forgot about that. I'll review/merge next time I get time.

**Comment by piranna** [comment] 2024-09-24 06:20
I have been waiting since several years to get my PRs for screen drawing merged, at least the one adding the ScreenBackend abstract class... That would fix and clean-up the rendering backend APIs and allow to add new ones later easily.

**Comment by astralstriker** [comment] 2024-10-17 10:41
I have a node project which uses canvas. I was looking to migrate it to deno. I believe 3.0.0-rc2 has a fix for missing node_module_register symbol error. When is the release planned for 3.0.0?

Here is the [link](https://github.com/denoland/deno/issues/26347) to the issue I opened in the deno repo.

**Comment by chearon** [comment] 2024-12-23 18:17
3.0 is released!

**Closed by chearon** 2024-12-23 18:17 UTC
