### ISSUE TITLE
npm run start error (canvas.node, 0x0001)

### ISSUE THREAD

**Issue by kokbee** [Automattic/node-canvas#2162] opened 2022-11-16 09:57 UTC
When I run it after installation, I get an error.
can you solve it? 🙇‍♂️

------

Environment
- node-canvas: 2.10.2
- node: 16.16.0
- npm: 9.1.1
- macOS: 12.6
- chip: Apple M1 Pro

------

Error 
```javascript
error: dlopen(node_modules/canvas/build/Release/canvas.node, 0x0001): symbol not found in flat namespace (_cairo_fill)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/flitto/flitto/qr-place/server/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

**Comment by sebhs** [comment] 2022-11-16 15:27
Seeing the same error

**Comment by kokbee** [comment] 2022-11-17 02:08
I tried all day yesterday.
As a result, it was resolved. 🙌

-----
```bash
1. remove brew
2. reinstall brew
3. set export PATH="/opt/homebrew"
4. arch -arm64 brew install pkg-config cairo pango libpng jpeg giflib librsvg
5. rm -rf node_modules
6. npm i
```
-----

**Comment by brettz9** [comment] 2022-12-27 05:44
I couldn't get the workaround to work, including by following the M1-chip-specific instructions at https://docs.brew.sh/Installation

**Comment by brettz9** [comment] 2022-12-27 13:19
Apologies, I *did* get this to work using the main installation at https://brew.sh/ . I previously had been directed to the alternative install page with the understanding that Apple Silicon wasn't supported by the default approach.

**Comment by zbjornson** [comment] 2023-12-28 22:39
Duplicate of https://github.com/Automattic/node-canvas/issues/2192. A few people posted their solutions there, please take a look.

**Closed by zbjornson** 2023-12-28 22:39 UTC
