### ISSUE TITLE
Package 'cairo' missing on Ubuntu

### ISSUE THREAD

**Issue by AsynchronousToddler** [Automattic/node-canvas#958] opened 2017-08-12 22:34 UTC
So, I'm trying to install this on my EC2 Ubuntu Instance, but getting this wonderful error

```
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
```

Ran the installation instructions for ubuntu

```
asynchronoustoddler@thetodlerlackey:~/The Toddler Lackey$ sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
g++ is already the newest version.
libgif-dev is already the newest version.
libjpeg-dev is already the newest version.
libcairo2-dev is already the newest version.
libpango1.0-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 61 not upgraded.
asynchronoustoddler@thetodlerlackey:~/The Toddler Lackey$ pkg-config --cflags cairo
Package xproto was not found in the pkg-config search path.
Perhaps you should add the directory containing `xproto.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xproto', required by 'xau', not found
asynchronoustoddler@thetodlerlackey:~/The Toddler Lackey$ dpkg-query -S cairo.pc
libcairo2-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/cairo.pc
libpango1.0-dev: /usr/lib/x86_64-linux-gnu/pkgconfig/pangocairo.pc
asynchronoustoddler@thetodlerlackey:~/The Toddler Lackey$ pkg-config --modversion cairo
1.13.1
asynchronoustoddler@thetodlerlackey:~/The Toddler Lackey$ pkg-config --modversion pango
1.36.3
```

## Your Environment
* Version of node-canvas (e.g. 1.6.6):
* Environment (e.g. node 7.10.0 on Ubuntu 14.04.5 LTS):

**Comment by melmsie** [comment] 2017-09-18 09:04
+1 for this, haven't been able to find a work around

**Comment by zbjornson** [comment] 2018-10-07 01:32
I think this is a duplicate of #735. Might try some of the suggestions there also.

**Closed by zbjornson** 2018-10-07 01:32 UTC
Labels: Installation help
