### ISSUE TITLE
Cant use fillText when used through Azure Function

### ISSUE THREAD

**Issue by mathieu-sylvain** [Automattic/node-canvas#1598] opened 2020-06-02 13:31 UTC
I'm using node-canvas inside Azure Function and I can't get text to be rendered correctly in the canvas I'm drawing to. Everything works well on my own setup but when I deploy it to Azure Function, deployment is said to be successful but I get weird results when drawing to canvas. I get the image you're seeing here. 

![image](https://user-images.githubusercontent.com/9437243/83525831-883cab00-a4b3-11ea-960e-3bb539f520a6.png)

I get this when I execute this :
- ctx.fillText(key, startingPoint.x, startingPoint.y)

Can someone help me figure out how to make this work, or what is causing this result ?

Thanks

**Comment by zbjornson** [comment] 2020-06-02 20:42
I think this is a duplicate of #857.

**Closed** 2020-06-05 15:25 UTC

**Comment by sherry2171** [comment] 2021-05-27 05:19
@mathieu-sylvain 
hello, could you please tell me how did you install node-canvas into AzureFunction?
I followed the steps from this website  [https://github.com/Automattic/node-canvas/wiki/Installation:-Windows](node-canvas)
and it worked well in my local environment. however, when I tried to use [npm install canvas] on kudu, i had an error like this. How did you solve the problem of installing the canvas module?
![image](https://user-images.githubusercontent.com/68887641/119769904-55769880-bef6-11eb-9c0c-f0363031cf35.png)

**Comment by mpalmahsf** [comment] 2023-07-22 15:24
@mathieu-sylvain  did you ever resolve this?  Running into the same issue when using fillText on an Azure Windows api app
