### ISSUE TITLE
Running out of memory when loading a specific image

### ISSUE THREAD

**Issue by nether-chicken** [Automattic/node-canvas#2282] opened 2023-08-31 01:54 UTC
## Issue
```
Error: out of memory
    at setSource (/root/chicken-bot/node_modules/canvas/lib/image.js:94:13)
    at /root/chicken-bot/node_modules/canvas/lib/image.js:62:11
    at /root/chicken-bot/node_modules/simple-get/index.js:97:7
    at PassThrough.<anonymous> (/root/chicken-bot/node_modules/simple-concat/index.js:8:13)
    at Object.onceWrapper (node:events:625:28)
    at PassThrough.emit (node:events:511:28)
    at PassThrough.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
canvas runs out of memory when trying to load a specific image. If the image is malformed, the error should be different

## Steps to Reproduce
```js
const Canvas = require('canvas')
Canvas.loadImage(`https://mc-heads.net/avatar/TiffaniX/16`)
```

## Your Environment
canvas@2.11.2

* Environment (e.g. node 4.2.0 on Mac OS X 10.8):
node v20.5.0 on Linux 6.4.11-arch2-1

**Comment by zbjornson** [comment] 2023-08-31 04:25
That image is missing the critical the `IEND` chunk and libpng fails to load it. That means this is a duplicate of #1612. I haven't looked into fixes for that issue, but would be happy to review a PR if you want to look into it.

**Closed by zbjornson** 2023-08-31 04:25 UTC
