### ISSUE TITLE
Text doesn't render for 100.X, 200.X, 300.X sizes

### ISSUE THREAD

**Issue by ddcovery** [Automattic/node-canvas#650] opened 2015-10-19 15:12 UTC
Just rendering a 24pt font using 300dpi I realized no text was rendering... conversion to px is 100.000000003937.
I realized that decimals when font size is 100, 200, 300 causes the "error" (nothing is rendered)

Try this

``` javascript
var canvas = new Canvas( 600, 300);
var ctx = canvas.getContext("2d");
ctx.patternQuality="best";
ctx.antialias = "subpixel";
ctx.textAlign = "center";
ctx.translate(300,150);
ctx.fillStyle = "white";
ctx.textBaseline = "middle";
ctx.font = "100.9px 'Helvetica'";
ctx.fillText("Source Sans Pro", 0, 0, 300);
var inStream = canvas.createJPEGStream({ quality: 94 });
var outStream = fs.createWriteStream("tmp/hola.jpeg");
inStream.pipe(outStream);
```

No text is rendered.

Decimals for 101 or 99 fotsizes work properly: 

size === 99.9 -> works
size === 100 -> works
size === 100.0 -> renders an small text, not the correct sized one
size === 100.5 -> nothing is rendered
size === 101 -> works
size == 101.1 -> works

The same is applicable to 200, 300, ...

**Comment by Jeiwan** [comment] 2016-05-17 04:03
I experience the same problem, but for 1001-1009, 2001-2009, 3001-3009 etc. font sizes. Here's the code that reproduces the bug:

```js
'use strict';

let Canvas = require('canvas');

let setFont = fontSize => `${fontSize}px sans-serif`;
let canvas = new Canvas(1000, 1000);
let ctx = canvas.getContext('2d');

ctx.font = setFont(999);
console.log(999, ctx.measureText('woot').width);
ctx.font = setFont(1001);
console.log(1001, ctx.measureText('woot').width);
ctx.font = setFont(1009);
console.log(1009, ctx.measureText('woot').width);
ctx.font = setFont(1010);
console.log(1010, ctx.measureText('woot').width);
console.log('---------------------------------');

ctx.font = setFont(1999);
console.log(1999, ctx.measureText('woot').width);
ctx.font = setFont(2001);
console.log(2001, ctx.measureText('woot').width);
ctx.font = setFont(2009);
console.log(2009, ctx.measureText('woot').width);
ctx.font = setFont(2010);
console.log(2010, ctx.measureText('woot').width);
console.log('---------------------------------');

ctx.font = setFont(2999);
console.log(2999, ctx.measureText('woot').width);
ctx.font = setFont(3001);
console.log(3001, ctx.measureText('woot').width);
ctx.font = setFont(3009);
console.log(3009, ctx.measureText('woot').width);
ctx.font = setFont(3010);
console.log(3010, ctx.measureText('woot').width);
```

Its output:

```
999 2111
1001 3
1009 20
1010 2134
---------------------------------
1999 4223
2001 3
2009 20
2010 4246
---------------------------------
2999 6335
3001 3
3009 20
3010 6359
```

**Comment by zbjornson** [comment] 2018-07-04 05:07
This is fixed in 2.x 🎉  (not sure which commit, probably since pango became required).

**Closed by zbjornson** 2018-07-04 05:07 UTC
Labels: Fixed?, Text & Fonts
