### ISSUE TITLE
Import SVG files

### ISSUE THREAD

**Issue by jakeg** [Automattic/node-canvas#494] opened 2014-12-17 09:24 UTC
Would love to be able to include SVG files in node-canvas documents (input/drawImage() them, not output to SVG) similar to JPG/PNGs etc.

**Comment by enagorny** [comment] 2015-03-05 11:06
+1

**Comment by mltucker** [comment] 2015-03-05 12:12
Cairo doesn't read SVG files, so this would require adding another dependency like librsvg.  Since librsvg works with cairo, it might be not that much work beyond adding the dependency.  Feel free to submit a patch!

**Comment by mori-dev** [comment] 2015-04-10 02:43
[fabric.js](http://fabricjs.com/) can help your goal.

**Comment by syadykin** [comment] 2015-05-13 07:27
+1 to this feature

**Comment by alex88** [comment] 2015-07-29 14:28
Maybe with http://cairosvg.org/ it can read them?

**Comment by karcass** [comment] 2015-10-16 03:13
+1

**Comment by jakeg** [comment] 2016-06-21 14:26
@mltucker are you sure cairo can't read svg files, or is it just that `node-canvas` doesn't yet have bindings to support them? I think surely the latter:

- http://cairosvg.org/ makes use of cairo to convert SVGs into PNG/PDF/etc

- https://cairographics.org/examples/ under 'SVG' says "Mozilla is using cairo to render SVG content as of Firefox 1.5 and 2.0. As of Firefox 3.0 it uses cairo for rendering all content and UI."

- https://wiki.gnome.org/action/show/Projects/LibRsvg says "librsvg is a library to render SVG files using cairo" with usage shown here: https://developer.gnome.org/rsvg/2.40/rsvg-Using-RSVG-with-cairo.html

... is importing SVGs not just a matter of requiring `librsvg` and for someone to add the necessary bindings as shown at https://developer.gnome.org/rsvg/2.40/rsvg-Using-RSVG-with-cairo.html ?

**Comment by jakeg** [comment] 2016-06-27 11:27
Happy to pay a bounty if anyone would like to work on this?

**Comment by yy1107** [comment] 2016-06-27 11:41
为什么我怎么感觉好像不是一起的了还是哪里出问题了

2016-06-27 19:27 GMT+08:00 Jake Gordon <notifications@github.com>:

**Comment by scott113341** [comment] 2016-06-30 00:33
I too would love this functionality.  @jakeg, does that bounty offer still stand?  😉

**Comment by jakeg** [comment] 2016-06-30 05:28
It sure does. I've emailed you to discuss :)

**Comment by yy1107** [comment] 2016-07-02 19:16
Mari sertai papan kumpulan 我的网站

我的网站: https://post.pinterest.com/f/a/0rZOeuzVntH4vm2kPgej4Q~~/AAAAAQA~/RgRZWpgdP0EIAOu1XQUQPJ5XCXBpbnRlcmVzdFgEAAAAAEgrQk9BUkRfQ09MTEFCT1JBVE9SX0lOVklURV9VTlJFR0lTVEVSRURfVVNFUkIKAAMdE3hXzRer-VJrcmVwbHkrMDExMDY3MDBmZWRhMThiMDMxN2Q2YzdlOWQ1YTczODUzNTJjNGNjMTk4NWRhZTAwOTJjZjAwMDAwMDAxMTM4OGNmOTM5MmExNjljZTAzMWNjNzE0QHJlcGx5LmdpdGh1Yi5jb20JUQQAAAAAREpodHRwczovL3d3dy5waW50ZXJlc3QuY29tL2lkZWFwYzExMDcvJUU2JTg4JTkxJUU3JTlBJTg0JUU3JUJEJTkxJUU3JUFCJTk5L0dCeyJiaW5kaW5nIjoibm90aWZpY2F0aW9ucyIsInQiOiI2MTc2Mjk5YTU0NmE0ZmNmOWEyYzc3ZGZlMmNhNjIyOSJ9
Terima jemputan: https://post.pinterest.com/f/a/UE7qEs_LSsL7YPEb2TOfaw~~/AAAAAQA~/RgRZWpgdP0EIAOu1XQUQPJ5XCXBpbnRlcmVzdFgEAAAAAEgrQk9BUkRfQ09MTEFCT1JBVE9SX0lOVklURV9VTlJFR0lTVEVSRURfVVNFUkIKAAMdE3hXzRer-VJrcmVwbHkrMDExMDY3MDBmZWRhMThiMDMxN2Q2YzdlOWQ1YTczODUzNTJjNGNjMTk4NWRhZTAwOTJjZjAwMDAwMDAxMTM4OGNmOTM5MmExNjljZTAzMWNjNzE0QHJlcGx5LmdpdGh1Yi5jb20JUQQAAAAAhC8BaHR0cHM6Ly93d3cucGludGVyZXN0LmNvbS9pZGVhcGMxMTA3LyVFNiU4OCU5MSVFNyU5QSU4NCVFNyVCRCU5MSVFNyVBQiU5OS8_dXRtX2NhbXBhaWduPW5ld3VzZXJib2FyZGludml0ZSZhbXA7dXRtX21lZGl1bT0yMDMzJmFtcDt1dG1fc291cmNlPTMxJmFtcDtlX3Q9NjE3NjI5OWE1NDZhNGZjZjlhMmM3N2RmZTJjYTYyMjkmYW1wO2ludml0ZXJfdXNlcl9pZD0yODQ3ODI1MTM4NDU0OTAwNzImYW1wO2ludml0ZV9jb2RlPTE1MTc1NzI2NWMxZTNlMWEwOGM4OTI1YzE2YzFhZjc2JmFtcDtib2FyZF9jb2xsYWJfaW52aXRlcj1UcnVlR0J7InQiOiI2MTc2Mjk5YTU0NmE0ZmNmOWEyYzc3ZGZlMmNhNjIyOSIsImJpbmRpbmciOiJub3RpZmljYXRpb25zIn0~



Baru dalam Pinterest?

Pinterest adalah alat penanda buku visual yang membantu anda menemui dan menyimpan idea kreatif—berseorangan atau bersama rakan. Gunakannya untuk memasak, melancong, pembaikan rumah dan banyak lagi!

Lihat cara Pinterest berfungsi: https://post.pinterest.com/f/a/5rx8t95NpeLysEVxn1yqUg~~/AAAAAQA~/RgRZWpgdP0EIAOu1XQUQPJ5XCXBpbnRlcmVzdFgEAAAAAEgrQk9BUkRfQ09MTEFCT1JBVE9SX0lOVklURV9VTlJFR0lTVEVSRURfVVNFUkIKAAMdE3hXzRer-VJrcmVwbHkrMDExMDY3MDBmZWRhMThiMDMxN2Q2YzdlOWQ1YTczODUzNTJjNGNjMTk4NWRhZTAwOTJjZjAwMDAwMDAxMTM4OGNmOTM5MmExNjljZTAzMWNjNzE0QHJlcGx5LmdpdGh1Yi5jb20JUQQAAAAARDxodHRwczovL3d3dy5waW50ZXJlc3QuY29tL18vXy9oZWxwL2d1aWRlL2FsbC1hYm91dC1waW50ZXJlc3RHQnsidCI6IjYxNzYyOTlhNTQ2YTRmY2Y5YTJjNzdkZmUyY2E2MjI5IiwiYmluZGluZyI6Im5vdGlmaWNhdGlvbnMifQ~~


Pinterest

Katalog idea dunia


572 7th Street, San Francisco, CA, 94103

Pusat Bantuan: https://post.pinterest.com/f/a/KCxnYnrqBVfq-ty5z3Xw5w~~/AAAAAQA~/RgRZWpgdP0EIAOu1XQUQPJ5XCXBpbnRlcmVzdFgEAAAAAEgrQk9BUkRfQ09MTEFCT1JBVE9SX0lOVklURV9VTlJFR0lTVEVSRURfVVNFUkIKAAMdE3hXzRer-VJrcmVwbHkrMDExMDY3MDBmZWRhMThiMDMxN2Q2YzdlOWQ1YTczODUzNTJjNGNjMTk4NWRhZTAwOTJjZjAwMDAwMDAxMTM4OGNmOTM5MmExNjljZTAzMWNjNzE0QHJlcGx5LmdpdGh1Yi5jb20JUQQAAAAARB9odHRwczovL3d3dy5waW50ZXJlc3QuY29tL2hlbHAvR0J7InQiOiI2MTc2Mjk5YTU0NmE0ZmNmOWEyYzc3ZGZlMmNhNjIyOSIsImJpbmRpbmciOiJub3RpZmljYXRpb25zIn0~

Dasar Privasi: https://post.pinterest.com/f/a/nReXG29vNjspjMDem9w-vQ~~/AAAAAQA~/RgRZWpgdP0EIAOu1XQUQPJ5XCXBpbnRlcmVzdFgEAAAAAEgrQk9BUkRfQ09MTEFCT1JBVE9SX0lOVklURV9VTlJFR0lTVEVSRURfVVNFUkIKAAMdE3hXzRer-VJrcmVwbHkrMDExMDY3MDBmZWRhMThiMDMxN2Q2YzdlOWQ1YTczODUzNTJjNGNjMTk4NWRhZTAwOTJjZjAwMDAwMDAxMTM4OGNmOTM5MmExNjljZTAzMWNjNzE0QHJlcGx5LmdpdGh1Yi5jb20JUQQAAAAARCxodHRwczovL3d3dy5waW50ZXJlc3QuY29tL18vXy9hYm91dC9wcml2YWN5L0dCeyJiaW5kaW5nIjoibm90aWZpY2F0aW9ucyIsInQiOiI2MTc2Mjk5YTU0NmE0ZmNmOWEyYzc3ZGZlMmNhNjIyOSJ9

Terma & Syarat: https://post.pinterest.com/f/a/sIxY9sVQIvwaC58M7xdNmA~~/AAAAAQA~/RgRZWpgdP0EIAOu1XQUQPJ5XCXBpbnRlcmVzdFgEAAAAAEgrQk9BUkRfQ09MTEFCT1JBVE9SX0lOVklURV9VTlJFR0lTVEVSRURfVVNFUkIKAAMdE3hXzRer-VJrcmVwbHkrMDExMDY3MDBmZWRhMThiMDMxN2Q2YzdlOWQ1YTczODUzNTJjNGNjMTk4NWRhZTAwOTJjZjAwMDAwMDAxMTM4OGNmOTM5MmExNjljZTAzMWNjNzE0QHJlcGx5LmdpdGh1Yi5jb20JUQQAAAAARCpodHRwczovL3d3dy5waW50ZXJlc3QuY29tL18vXy9hYm91dC90ZXJtcy9HQnsiYmluZGluZyI6Im5vdGlmaWNhdGlvbnMiLCJ0IjoiNjE3NjI5OWE1NDZhNGZjZjlhMmM3N2RmZTJjYTYyMjkifQ~~

Berhenti melanggan e-mel ini: https://post.pinterest.com/f/a/O2OCSdExHZ3Lzt7nbG9Oag~~/AAAAAQA~/RgRZWpgdP0EIAOu1XQUQPJ5XCXBpbnRlcmVzdFgEAAAAAEgrQk9BUkRfQ09MTEFCT1JBVE9SX0lOVklURV9VTlJFR0lTVEVSRURfVVNFUkIKAAMdE3hXzRer-VJrcmVwbHkrMDExMDY3MDBmZWRhMThiMDMxN2Q2YzdlOWQ1YTczODUzNTJjNGNjMTk4NWRhZTAwOTJjZjAwMDAwMDAxMTM4OGNmOTM5MmExNjljZTAzMWNjNzE0QHJlcGx5LmdpdGh1Yi5jb20JUQQAAAAAhHwDaHR0cHM6Ly93d3cucGludGVyZXN0LmNvbS9lbWFpbC91bnN1YnNjcmliZS8_b2Q9aW1zd09UVHdiMjB4N3ElMkZQWnlPdmx1NUNVcWRVOWdiTG92cHpZNFJnWk1QbTMzTnhPWUN6aUtqV0drTVFFSjBMdzdpcjQ2NzBRdGRTJTBBUm5CV0c0UUlheE5LSks5c0V3eVVaazlDbVd2WXU4cE5QNjNNZGk4dmowJTJGaVg5MW9QUjZ5aGtvd0xGcTglMkZnbk9veW1wTDI1TDBjYmclMEExV2YzbVhzMmROJTJGRmFzRkxJWmx6MUwwUE56c0ZrWUhOcVV4czh5akd3ZDZybHFLOHdWUFpoZ0E3bEtPV1htbzJhaEtOS1Y1aFF6UmolMEFGMTZNMzE4N2xvVmlybHpEJTJGZkZkZSUyQlF2bTg3bGgyJTJGNmFDdHh6WGlMZ1JkcEw2QVRCZE9DWVdMbDEwb0FsRm0yenhmWmZFRVNVaCUyRjUlMEFNb3pmeXh1b0RYUTQlMkI0SnBBZ01FRnJqOXVwMk0wdmxYTFhCbWw1Z3I4aFNOMnFjY1pNMFllRVdVWXRkRWhkY2duSUJXTHBjeiUyQm5mRSUwQUxvMVF3ZFRKRnNBUXNBb0hZbnRkRW9La1pzNlVYT3lWUzdrNGFLd0ZpZFUwRnVWeGFJdHN3UnhKbVpkUlpycEdYNUlmTHB0QVh2Q3clMEFvNVRydG8wTDJZNDNvV1lHUjRzYUtJV1lNazFTT0dGNCUyQnR4a0dLYlRmJTJGVmJPeDlNajhmYXY3dnhMYUFFTyUyQktXUWpJaTFuYU4xcFV5JTBBNDZDNjZNbDNYTFlzUlpKOHVpcnlVTGc3aCUyRlUwQUJDSVJvZWljcVMwTHVFUmF3M1dzekVEeEJ6cFdYQ3R4MEtWVmJrWFQzbktHZTBZJTBBJTJGNEZVZG5WSGpOTSUzRCUwQSZhbXA7dXNlcl9pZD1jbVZ3Ykhrck1ERXhNRFkzTURCbVpXUmhNVGhpTURNeE4yUTJZemRsT1dRMVlUY3pPRFV6TlRKak5HTmpNVGs0TldSaFpUQXdPVEpqJTBBWmpBd01EQXdNREF4TVRNNE9HTm1PVE01TW1FeE5qbGpaVEF6TVdOak56RTBRSEpsY0d4NUxtZHBkR2gxWWk1amIyMCUzRCUwQUdCeyJ0IjoiNjE3NjI5OWE1NDZhNGZjZjlhMmM3N2RmZTJjYTYyMjkiLCJiaW5kaW5nIjoibm90aWZpY2F0aW9ucyJ9

**Comment by karcass** [comment] 2016-07-02 20:17
I'd be willing to kick in.

**Comment by scott113341** [comment] 2016-07-02 21:24
To keep everyone updated, I am currently working on adding this functionality: https://github.com/scott113341/node-canvas/tree/svg

I have a couple demos in the `svg-demo/` directory: https://github.com/scott113341/node-canvas/tree/svg/svg-demo

**Comment by chearon** [comment] 2016-07-03 01:54
@scott113341 nice, bummer we have to add another dependency though ☹️

**Comment by scott113341** [comment] 2016-07-03 18:48
Another option is to do something like [this](http://www.professorcloud.com/svg-to-canvas/), where SVG geometry is parsed and then drawn onto the canvas.  My guess is that this approach wouldn't work for all SVGs, but it's worth investigating.

**Comment by yy1107** [comment] 2016-07-03 19:12
我不是这个意思我现在正在学如何做服务器上做好项目。可是我现在根本不会如何上传代码。还有我现在不知道该怎么用什么平台传送。实在是我的不对希望多多体谅。比如你教教我。我是真心讨教😭

2016-07-04 2:48 GMT+08:00 Scott Hardy <notifications@github.com>:

**Comment by jakeg** [comment] 2016-07-04 08:26
@scott113341 Yeah I was thinking about using ``canvg`` before and it's still a backup idea. However, from the progress you've made so far I've got my fingers crossed we'll be able to properly import svgs soon :)

@chearon is it really a problem to have another dependency?

**Comment by yy1107** [comment] 2016-07-04 12:42
能否教教我怎么设置邮件我现在服务器邮箱都饱满了

2016-07-04 16:26 GMT+08:00 Jake Gordon <notifications@github.com>:

**Comment by chearon** [comment] 2016-07-04 15:00
@jakeg most of the issues posted here are with dependencies. I'm working on distributed static builds though so if that gets merged it would be less of a problem. In the meantime it's worth considering having the SVG library be built only if it's found on the system, the same way Pango currently is on master

**Comment by jakeg** [comment] 2016-09-10 06:59
Just noticed pull request #406 from 2 years ago which claims to add this functionality I think?

**Comment by foysavas** [comment] 2016-09-10 15:11
@scott113341 what's outstanding from your branch? I am planning to reapply #406 over current master and create a new PR, but want to check in with you about your work first.

**Comment by jakeg** [comment] 2016-09-10 16:10
If I remember correctly from a couple of months ago, Scott's fork was working for some SVGs but mangling other ones. Also, if outputting as PDF, the SVGs were unfortunately placed as low res rasters in the PDF output, rather than being placed as-is in their original vector form.

**Comment by foysavas** [comment] 2016-09-10 21:21
Thanks for the insight @jakeg.

* Mangling SVGs is definitely bad. I will look to confirm why and when this happens.
* Low-res raster renderings of SVGs in PDF output, however, may be acceptable. After all, the SVG is first rendered within an img element contained within a canvas of set size.
* As also requested, I will also make sure the next PR doesn't impose any new hard dependency requirements on node-canvas

As a next step, I will assess both @scott113341 and @petarov approaches and report back with any serious issues.

Do we have someone with merge privileges watching this discussion? I want to make sure the next PR doesn't lose our momentum.

Thanks again all!

**Comment by jakeg** [comment] 2016-09-11 06:52
@foysavas if the SVG is inserted in the PDF at a good resolution (maybe adding an option somehow to specify this?), then this may just be good enough. However, the current code puts them in at a ghastly low resolution with a lot of JPG artifacts (or similar), if I remember correctly.

Ideally for my use though, the SVG would be inserted as-is. I'm printing around 50,000 books a year, using html5 canvas on the front end for users to design pages, and node-canvas on the server to produce PDFs which I then send to print. Clearly I'm going to need the SVGs to end up at a printable quality!

**Comment by foysavas** [comment] 2016-09-12 04:24
Hi all, please try out #811 and tell me if there are any issues.

**Comment by jakeg** [comment] 2016-09-13 10:25
This works fine with tree.svg, but not with the attached ok.svg (gah, github doesn't allow svg attach, so please rename from ok.png to ok.svg and then try it)

Here's the ok.svg file (saved as ok.png to get it to upload):

![ok](https://cloud.githubusercontent.com/assets/744792/18470383/2e1e7baa-79a4-11e6-862c-19dc2235781e.png)

Here's the mangled output:

![demo-1](https://cloud.githubusercontent.com/assets/744792/18470400/43dad966-79a4-11e6-83cc-c177027c4469.png)

Also can confirm that PDF output is same as per Scott's code (low-quality raster version of the svg rather than original vector file placed as-is in the pdf)

**Comment by foysavas** [comment] 2016-09-13 13:09
@jakeg What OS and version of librsvg and node are you using? I managed to render ok.svg without issue.

![ok](https://cloud.githubusercontent.com/assets/1735/18474729/8951514a-7991-11e6-9f7f-bd905f47f1a9.png)

**Comment by jakeg** [comment] 2016-09-14 08:09
@foysavas Ubuntu 14.04 (in a VM on Windows 10), Node v4.4.5 and librsvg 2 (installed with `sudo apt-get install librsvg2-dev`)

**Comment by petarov** [comment] 2016-09-14 20:33
Just for the record, it looks godo on my Arch Linux w/h node 6.5.0. 

@jakeg Does the mangling occur only with this particular SVG or also with other ones you got?

**Comment by foysavas** [comment] 2016-09-14 20:57
I can confirm the bad rendering of ok.svg on Ubuntu 14.04, using Node v4 or v6, and the packaged librsvg version 2.40.2.

In contrast, I can confirm a correct rendering of ok.svg on Ubuntu 16.04, using Node v4 or v6, and the packaged librsvg version 2.40.13.

I believe that librsvg around version 2.40.2 has a path parsing bug and that by 2.40.13 it was fixed. This abandoned bug post seems to support that: https://bugzilla.gnome.org/show_bug.cgi?id=767919

@jakeg Ubuntu 16.04 is also a LTS, hopefully you can transition to it. If you still run into issues, tell me.

**Comment by jakeg** [comment] 2016-09-15 08:11
@foysavas fantastic! Yes, I am upgrading the main server to Ubuntu 16.04 today, and was going to run a new test after the upgrade, so wonderful to hear that :)

Has anyone had a look at PDF output at all yet? See below re the quality of the SVG in the PDF (although it says it does, github doesn't allow me to add a PDF so again just change file extension from png to pdf)

![tree pdf](https://cloud.githubusercontent.com/assets/744792/18542735/45083186-7b24-11e6-92b2-7aa0e66d4f9e.png)

**Comment by foysavas** [comment] 2016-10-03 14:51
@jakeg Glad to hear it! Native SVGs embedded in PDFs would be nice. Maybe the best way to implement it would be to use `MODE_MIME` as can be done with JPEGs. I'll spend some cycles to make it happen, but let's get PR #811 merged in first. I'm afraid deviating too much from master will put the PR at risk for going stale.

**Comment by zbjornson** [comment] 2018-03-14 03:42
Closing since the corresponding PR for this landed in 2.x! 🎉

**Closed by zbjornson** 2018-03-14 03:42 UTC

**Comment by usr-ein** [comment] 2022-09-06 15:07
Just linking the PR mentionned above, if anyone ends up on this issue and wants to know what the PR was: 

#811
