### ISSUE TITLE
can't render image color with CMYK

### ISSUE THREAD

**Issue by windreamlion** [Automattic/node-canvas#1090] opened 2018-02-10 05:02 UTC
## Issue
i find node-canvas can't render image color when image color space is CMYK

##Environment
* Version of node-canvas 1.6.9:
* Environment (node 9.0.0 on Mac OS X 10.13):

**Comment by zbjornson** [comment] 2018-02-13 05:49
Dupe of #425.

**Closed by zbjornson** 2018-02-13 05:49 UTC
