### ISSUE TITLE
【issue】NAN_METHOD(Image::SetSource) does not support Chinese

### ISSUE THREAD

**Issue by fantasticsoul** [Automattic/node-canvas#1704] opened 2020-11-16 03:49 UTC
## Issue
can read image path that includ chinese string in windows os
> but it works in mac os
see https://github.com/tnfe/FFCreator/issues/3

**Comment by zbjornson** [comment] 2021-05-20 11:00
Closing as a duplicate of #1802, which has a bit more information.

**Closed by zbjornson** 2021-05-20 11:00 UTC
