### ISSUE TITLE
node-canvas fails to install, build output shows type conversion error

### ISSUE THREAD

**Issue by logicbomb421** [Automattic/node-canvas#1075] opened 2018-01-15 03:08 UTC
When installing, the node-gyp build phase eventually fails with a `make failed with exit code 2` message. Looking through the build output (full output below), I noticed the following:

> ../src/CanvasRenderingContext2d.cc:525:65: error: invalid conversion from ‘int’ to ‘cairo_format_t {aka _cairo_format}’ [-fpermissive]
else if (!strcmp(*utf8PixelFormat, "RGB16_565")) format = CAIRO_FORMAT_RGB16_565;

My guess is this is causing make to fail. I have followed the installation instructions in the readme (specifically: `sudo yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel`), however this error still appears.

### Full Output
```

> bcrypt@1.0.3 install /var/project/web/node_modules/@project/core/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/var/project/web/node_modules/@project/core/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> canvas@2.0.0-alpha.9 install /var/project/web/node_modules/canvas
> node-gyp rebuild

make: Entering directory `/var/project/web/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/backend/Backend.o
  CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o
../src/backend/ImageBackend.cc: In member function ‘int32_t ImageBackend::approxBytesPerPixel()’:
../src/backend/ImageBackend.cc:28:3: warning: case value ‘4’ not in enumerated type ‘cairo_format_t {aka _cairo_format}’ [-Wswitch]
   case CAIRO_FORMAT_RGB16_565:
   ^
  CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o
In file included from ../src/backend/PdfBackend.cc:4:0:
/usr/include/libpng12/png.h:2657:31: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^
/usr/include/libpng12/png.h:2665:31: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^
/usr/include/libpng12/png.h:2673:31: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^
  CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o
In file included from ../src/backend/SvgBackend.cc:4:0:
/usr/include/libpng12/png.h:2657:31: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^
/usr/include/libpng12/png.h:2665:31: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^
/usr/include/libpng12/png.h:2673:31: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^
  CXX(target) Release/obj.target/canvas/src/Backends.o
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/PNG.h:3:0,
                 from ../src/Canvas.cc:18:
/usr/include/libpng12/png.h:2657:31: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^
/usr/include/libpng12/png.h:2665:31: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^
/usr/include/libpng12/png.h:2673:31: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^
In file included from ../src/Canvas.cc:18:0:
../src/PNG.h: In function ‘cairo_status_t canvas_write_png(cairo_surface_t*, png_rw_ptr, canvas_png_write_closure_t*)’:
../src/PNG.h:19:31: warning: case label value is less than minimum value for type [enabled by default]
 #define CAIRO_FORMAT_INVALID -1
                               ^
../src/PNG.h:200:10: note: in expansion of macro ‘CAIRO_FORMAT_INVALID’
     case CAIRO_FORMAT_INVALID:
          ^
../src/PNG.h:196:5: warning: case value ‘4’ not in enumerated type ‘cairo_format_t {aka _cairo_format}’ [-Wswitch]
     case CAIRO_FORMAT_RGB16_565:
     ^
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
../src/CanvasRenderingContext2d.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Context2d::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/CanvasRenderingContext2d.cc:525:65: error: invalid conversion from ‘int’ to ‘cairo_format_t {aka _cairo_format}’ [-fpermissive]
         else if (!strcmp(*utf8PixelFormat, "RGB16_565")) format = CAIRO_FORMAT_RGB16_565;
                                                                 ^
../src/CanvasRenderingContext2d.cc: In static member function ‘static Nan::NAN_GETTER_RETURN_TYPE Context2d::GetFormat(v8::Local<v8::String>, Nan::NAN_GETTER_ARGS_TYPE)’:
../src/CanvasRenderingContext2d.cc:558:3: warning: case value ‘4’ not in enumerated type ‘cairo_format_t {aka _cairo_format}’ [-Wswitch]
   case CAIRO_FORMAT_RGB16_565: pixelFormatString = "RGB16_565"; break;
   ^
../src/CanvasRenderingContext2d.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Context2d::PutImageData(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/CanvasRenderingContext2d.cc:738:3: warning: case value ‘4’ not in enumerated type ‘cairo_format_t {aka _cairo_format}’ [-Wswitch]
   case CAIRO_FORMAT_RGB16_565: {
   ^
../src/CanvasRenderingContext2d.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE Context2d::GetImageData(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/CanvasRenderingContext2d.cc:907:3: warning: case value ‘4’ not in enumerated type ‘cairo_format_t {aka _cairo_format}’ [-Wswitch]
   case CAIRO_FORMAT_RGB16_565: {
   ^
make: *** [Release/obj.target/canvas/src/CanvasRenderingContext2d.o] Error 1
make: Leaving directory `/var/project/web/node_modules/canvas/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.49-moby
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/project/web/node_modules/canvas
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-test-renderer@15.6.2 requires a peer of react@^15.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-timeseries-charts@0.12.8 requires a peer of react@^15.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.0.0-alpha.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.0.0-alpha.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-13T06_52_11_596Z-debug.log
```

## Steps to Reproduce
Attempting to install this package into my project produces the described behavior.

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2.0.0-alpha.9
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): CentOS 7 (running inside a Docker container)
* Node version: 8.9.3
* Node-gyp version: 3.6.2

**Comment by suifengfengye** [comment] 2018-01-23 01:01
@logicbomb421 Have you fixed this problem?

**Comment by zbjornson** [comment] 2018-01-23 01:10
Cross-posting my comment from here: https://github.com/Automattic/node-canvas/issues/1067#issuecomment-359633566

> can you try using canvas-prebuilt instead please? CentOS's default package manger ships an ancient version of Cairo (>10 years old) that isn't supported by node-canvas. `npm install canvas-prebuilt@next` or `yarn add canvas-prebuilt@next`.

**Comment by suifengfengye** [comment] 2018-01-23 01:25
@zbjornson I use `canvas-prebuilt` first! But when I'm draw Chinese in the canvas, it show messy code.(I'm Chinese). I cannot find a function to register font  when I use `canvas-prebuilt`. So I have to use `node-canvas`.

**Comment by zbjornson** [comment] 2018-01-23 01:48
Argh, looks like canvas-prebuilt hasn't been released with [this](https://github.com/node-gfx/node-canvas-prebuilt/commit/362a0a6b883dcf8b5ddfba6b209b7d20ff258faa) commit in it yet. You could make that change manually until @chearon has time to publish an update. The only other option is obtaining a more recent Cairo library (or switching off of CentOS), which is not something I can really help with (haven't done it myself).

**Comment by suifengfengye** [comment] 2018-01-23 03:41
@zbjornson Thank you! I found I can use FontConfig with `canvas-prebuilt` to fixed this issuse.

**Comment by pvencill** [comment] 2018-06-25 19:02
I'm still getting the same error on Mac High Sierra, and using `canvas-prebuilt@next` does not solve it.

**Comment by zbjornson** [comment] 2018-07-07 03:33
@pvencill I haven't seen anyone using an old version of Cairo on Mac High Sierra, which was the cause of this bug. You hit the exact issue in the original post?

**Closed by zbjornson** 2018-07-07 03:33 UTC
Labels: Installation help
