### ISSUE TITLE
Add ARM prebuilts

### ISSUE THREAD

**Issue by LukasDoesDev** [Automattic/node-canvas#1699] opened 2020-11-07 20:27 UTC
## Issue or Feature
Could you add ARM prebuilts as i got these warnings:
```
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-linux-glibc-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@15.1.0 (node-v88 ABI, glibc) (falling back to source compile with node-gyp)
```

## Steps to Reproduce
Uh, get a raspberry pi, get 2020-08-20 raspberry pi os lite get node with nvm and try to install node-canvas https://github.com/Automattic/node-canvas/wiki/Installation:-Ubuntu-and-other-Debian-based-systems

## Your Environment
* canvas@2.6.1
* Node v15.1.0 on [2020-08-20-raspios-buster-armhf-lite.img](https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2020-08-24/2020-08-20-raspios-buster-armhf-lite.zip)

**Comment by zbjornson** [comment] 2020-11-09 02:09
Duplicate of #1662. Not sure when this will happen since I'm still struggling to get x86/64 prebuilds working again.

See also, from #1511, another place to track this issue:

> Prebuilds aren't available for ARM. Please see the [wiki](https://github.com/Automattic/node-canvas/wiki#installation-guides) for guides on building from source. See also https://github.com/node-gfx/node-canvas-prebuilt/issues/69.

**Closed by zbjornson** 2020-11-09 02:09 UTC

**Comment by christianhaller3000** [comment] 2022-01-11 09:06
Thanks for the documentation.
`brew install pkg-config cairo pango libpng jpeg giflib librsvg` was helping me on my M1

**Comment by eniac111** [comment] 2023-04-27 10:25
Do you want any help with CI/CD? :)
