### ISSUE TITLE
ctx.font with multiple fonts results in default font on macOS

### ISSUE THREAD

**Issue by pravdomil** [Automattic/node-canvas#1189] opened 2018-06-27 15:47 UTC
## Bug

Setting `ctx.font` to multiple fonts like: `"30px Courier, 'Times New Roman'"` sets font family to default font, see output:

![image](https://user-images.githubusercontent.com/2387356/41984713-9f34d5d4-7a31-11e8-82e7-230c7137e213.png)

## Steps to Reproduce

```js
const { createCanvas } = require("canvas")
const canvas = createCanvas(200, 200)
const ctx = canvas.getContext("2d")

// Write "Awesome!"
ctx.font = "30px Courier, 'Times New Roman'"
ctx.rotate(0.1)
ctx.fillText("Awesome!", 50, 100)

console.log('<img src="' + canvas.toDataURL() + '" />')
```

## Your Environment
* Version of node-canvas (e.g. 1.4.0): 2.0.0-alpha.12
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): node 10.1.0, macOS 10.13.5

**Comment by chearon** [comment] 2018-06-27 19:38
That's a bug in Pango for macOS, I submitted a patch [here](https://gitlab.gnome.org/GNOME/pango/issues/252#note_182403) but it's not integrated still.

**Comment by pravdomil** [comment] 2018-06-27 20:00
I know that this bug is not related to this repository, but can you leave it open so that people will aware of it?

**Comment by chearon** [comment] 2018-06-27 20:10
Fair enough

**Comment by pravdomil** [comment] 2018-06-27 20:17
I have created PR https://gitlab.gnome.org/GNOME/pango/merge_requests/4

**Comment by asturur** [comment] 2018-09-03 20:53
duplicate of #977?

**Comment by pravdomil** [comment] 2018-09-11 18:04
yes

**Closed** 2018-09-11 18:06 UTC
Labels: Bug
