### ISSUE TITLE
drawImage fails with setTransform 2.5.0

### ISSUE THREAD

**Issue by mpahima** [Automattic/node-canvas#1431] opened 2019-06-04 12:54 UTC
Hi, there's a bug in 2.5.1
when im doing setTransform(1.0007160803321118,-0.05395164954833996,0.019562259239278124,0.9889808837634921,131.75,17.25)
and drawing an image it retuned as black for some reason

width = 287.29427422070216
height = 230.0347799790284
x = 0
y = 0

**VERSION 2.4.1 IT WORKS PERFECTLY**

**Comment by zbjornson** [comment] 2019-06-04 16:26
Thanks for reporting. Could you post a full, short code snippet that we can run to reproduce the issue please?

**Comment by zbjornson** [comment] 2019-06-10 05:50
@mpahima I can't reproduce this with the code below:

```js
const {createCanvas, loadImage} = require("canvas");
const fs = require("fs");

const canvas = createCanvas(300, 300);
const ctx = canvas.getContext("2d");
ctx.setTransform(1.0007160803321118,-0.05395164954833996,0.019562259239278124,0.9889808837634921,131.75,17.25);
loadImage("./test/fixtures/chrome.jpg").then(img => {
	ctx.drawImage(img, 0, 0);
	fs.writeFileSync("test.png", canvas.toBuffer());
});
```

**Comment by Flicksie** [comment] 2019-07-01 17:42
this probably is related to #1417 's issue with numbers that are too precise

**Comment by zbjornson** [comment] 2019-07-23 01:09
Assuming this was fixed by https://github.com/Automattic/node-canvas/commit/81cf69bf1fe15f07083e42f96e86ea20c8bb9f87. If you're still seeing the issue, please let us know.

**Closed by zbjornson** 2019-07-23 01:09 UTC
Labels: Needs more info
