### ISSUE TITLE
Command failed：node-pre-gyp install --fallback-to-build --update-binary

### ISSUE THREAD

**Issue by da-du** [Automattic/node-canvas#2186] opened 2023-01-03 08:02 UTC
## Steps to Reproduce
When I run `yarn`, the error is as follows:
```
warning Error running install script for optional dependency: "/Users/XXX/project/saas-statistics/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build --update-binary
Arguments: 
Directory: /Users/XXX/project/saas-statistics/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@16.19.0 | darwin | arm64
node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v93-darwin-unknown-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v93-darwin-unknown-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.0 and node@16.19.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v93-darwin-unknown-arm64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@16.19.0 | darwin | arm64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@16.19.0 | darwin | arm64
gyp info find Python using Python version 3.8.9 found at \"/Library/Developer/CommandLineTools/usr/bin/python3\"
gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/XXX/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/XXX/project/saas-statistics/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/XXX/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/XXX/Library/Caches/node-gyp/16.19.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/XXX/Library/Caches/node-gyp/16.19.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/XXX/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/XXX/Library/Caches/node-gyp/16.19.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/XXX/project/saas-statistics/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: pkg-config: command not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/XXX/node_modules/node-gyp/lib/configure.js:325:16)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command \"/Users/XXX/.nvm/versions/node/v16.19.0/bin/node\" \"/Users/XXX/node_modules/node-gyp/bin/node-gyp.js\" \"configure\" \"--fallback-to-build\" \"--update-binary\" \"--module=/Users/XXX/project/saas-statistics/node_modules/canvas/build/Release/canvas.node\" \"--module_name=canvas\" \"--module_path=/Users/XXX/project/saas-statistics/node_modules/canvas/build/Release\" \"--napi_version=8\" \"--node_abi_napi=napi\" \"--napi_build_version=0\" \"--node_napi_label=node-v93\"
gyp ERR! cwd /Users/XXX/project/saas-statistics/node_modules/canvas
gyp ERR! node -v v16.19.0
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/XXX/.nvm/versions/node/v16.19.0/bin/node /Users/XXX/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/XXX/project/saas-statistics/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/XXX/project/saas-statistics/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/XXX/project/saas-statistics/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1100:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
node-pre-gyp ERR! System Darwin 21.6.0
node-pre-gyp ERR! command \"/Users/XXX/.nvm/versions/node/v16.19.0/bin/node\" \"/Users/XXX/project/saas-statistics/node_modules/canvas/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build\" \"--update-binary\"
node-pre-gyp ERR! cwd /Users/XXX/project/saas-statistics/node_modules/canvas
node-pre-gyp ERR! node -v v16.19.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok 
Failed to execute '/Users/XXX/.nvm/versions/node/v16.19.0/bin/node /Users/XXX/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/Users/XXX/project/saas-statistics/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/XXX
[5/5] ♻️  Cleaning modules...
success Saved lockfile.
✨  Done in 94.91s.
```

This is the information for  run `yarn why canvas`：
```
yarn why v1.22.19
warning ../../package.json: No license field
[1/4] 🤔  Why do we have the module "canvas"...?
[2/4] 🚚  Initialising dependency graph...
warning Lockfile has incorrect entry for "antd@3.10.2". Ignoring it.
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "canvas@2.11.0"
info Reasons this module exists
   - "@types#react-pdf#@types#pdfjs-dist#pdfjs-dist" depends on it
   - Hoisted from "@types#react-pdf#@types#pdfjs-dist#pdfjs-dist#canvas"
✨  Done in 0.91s.
```

## Your Environment
* canvas@2.11.0
* node 16.19.0 on Mac OS X 12.5

**Comment by jarmitage** [comment] 2023-01-03 08:36
Same issue of 404 at https://github.com/Automattic/node-canvas/releases/download/v2.11.0/canvas-v2.11.0-node-v108-darwin-unknown-arm64.tar.gz

macOS 12.6

**Comment by jarmitage** [comment] 2023-01-03 09:05
Fixed for me: `brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman`

**Comment by da-du** [comment] 2023-01-03 10:11
> Fixed for me: `brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman`

But is it the right way to pack so many packages?

**Comment by MrDzi** [comment] 2023-01-24 11:29
The issue stays the same for me even after running `brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman`.
This is odd as I saw this to be a solution for many people in multiple places.

**Comment by Kaisarion** [comment] 2023-01-26 18:01
can reproduce - macbook m1 ventura on a docker container
any fixes? have tried everything from a source build to an npm ci

**Comment by Orange-001** [comment] 2023-05-25 01:43
Hey, guys! I also had the same issue and solved it. Maybe you can try creating an .npmrc file under the project root path, specifying the mirror address of the canvas, like this:

**Comment by Orange-001** [comment] 2023-05-25 01:44
Hey, guys! I also had the same issue and solved it. Maybe you can try creating an .npmrc file under the project root path, specifying the mirror address of the canvas, like this:

**Comment by Orange-001** [comment] 2023-05-25 01:51
Hey, guys! I also had the same issue. Maybe you can try creating an .npmrc file under the project root path, specifying the mirror address of the canvas, like this: `canvas_binary_host_mirror=https://registry.npmmirror.com/-/binary/canvas`
It worked for me and I hope it helps you.

**Comment by LijiaHou** [comment] 2023-05-26 07:46
> Hey, guys! I also had the same issue. Maybe you can try creating an .npmrc file under the project root path, specifying the mirror address of the canvas, like this: `canvas_binary_host_mirror=https://registry.npmmirror.com/-/binary/canvas` It worked for me and I hope it helps you.

**Comment by LijiaHou** [comment] 2023-05-26 07:47
Wow, bro, you're so cool！ I installed it in the Windows environment for two days without success until I used your method!

**Comment by LijiaHou** [comment] 2023-05-26 07:48
> Hey, guys! I also had the same issue. Maybe you can try creating an .npmrc file under the project root path, specifying the mirror address of the canvas, like this: `canvas_binary_host_mirror=https://registry.npmmirror.com/-/binary/canvas` It worked for me and I hope it helps you.

Wow, bro, you're so cool！ I installed it in the Windows environment for two days without success until I used your method!

**Comment by JianLin176** [comment] 2023-07-15 20:24
> 大家好！我也有同样的问题。也许您可以尝试在项目根路径下创建一个 .npmrc 文件，指定画布的镜像地址，如下所示：`canvas_binary_host_mirror=https://registry.npmmirror.com/-/binary/canvas`
> 它对我有用，希望对您有所帮助。

it work for me too.

**Comment by Whobeu** [comment] 2023-12-11 19:33
> > > Fixed for me: `brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman`
> > 
> > 
> > But is it the right way to install so many packages?
> 
> Looks it's expected way based on the canvas documentation - https://github.com/Automattic/node-canvas/wiki/Installation%3A-Mac-OS-X

I have several Raspberry's that I use with node-canvas. Finally created myself a tiny bash script to handle it:

```
#!/bin/bash

read -p "Do you want to install the libraries for node-canvas? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
  echo Installing packages required for installation of node-canvas
  sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
fi
```

There was a reason the -dev packages were required but I have forgotten.

**Comment by 335296558** [comment] 2024-01-12 08:47
> Fixed for me: `brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman`

Mine is m1, this method helped me solve the problem

**Comment by Imeth97** [comment] 2024-01-28 00:33
I have the same issue, running 
`yarn install --ignore-optional `
has fixed it for me for now. Canvas is only an optional dependency for react-pdf it seems

**Comment by Suyash-Purwar** [comment] 2024-02-08 15:51
> Fixed for me: `brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman`

This doesn't fix anything for me. Using node version `v14.21.3` on macOS 14.

**Comment by bora001** [comment] 2024-06-05 05:21
> Fixed for me: `brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman`

Brew install doesn't work for me, but after adding "node-gyp," it works fine.

- Solved : Added "node-gyp"
```
   "node-gyp": "^10.1.0",
```

- Environment
```
  "canvas": "^2.11.2"
  "node": ">= v18.18.1",
  Mac : M1 macOS Ventura 13.4
```

**Comment by tiennguyen1293** [comment] 2024-10-28 06:57
I followed this step and its worked for me
https://github.com/wojtekmaj/react-pdf/issues/1589#issuecomment-1692943626

**Comment by jose-aiq** [comment] 2024-10-29 14:21
> Fixed for me: brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman

This work for me, running on mac m1 with macos 15.0.1

**Comment by Aarbel** [comment] 2024-10-30 20:29
Solution that definitely solved the problem for us, just run the npm install or yarn inside python environment:

```
python3 -m venv venv
source venv/bin/activate
pip install setuptools wheel

yarn

deactivate 
```

**Comment by chearon** [comment] 2024-12-08 00:12
There are several different types of issues in the comments, but since #2354 was merged, I don't think the issue in the OP would happen so I'm going to close it. Following the install instructions (https://github.com/Automattic/node-canvas/issues/2186#issuecomment-1369528914) also would have worked.

`npm install canvas@next` to get 3.0.0-rc3. I'm going to wait a few days before releasing 3.0.

**Closed by chearon** 2024-12-08 00:12 UTC

**Comment by SHADDOCKTREE** [comment] 2024-12-13 07:39
> There are several different types of issues in the comments, but since [#2354](https://github.com/Automattic/node-canvas/pull/2354) was merged, I don't think the issue in the OP would happen so I'm going to close it. Following the install instructions ([#2186 (comment)](https://github.com/Automattic/node-canvas/issues/2186#issuecomment-1369528914)) also would have worked.
> 
> `npm install canvas@next` to get 3.0.0-rc3. I'm going to wait a few days before releasing 3.0.

that works for me ！！
mac M2
nvm v0.40.1
node v23.4.0
