### ISSUE TITLE
non-context-aware native module

### ISSUE THREAD

**Issue by jeffg2k** [Automattic/node-canvas#1702] opened 2020-11-12 21:45 UTC
Seeing this while running an Electron app.
```
Uncaught Error: Loading non-context-aware native module in renderer: './node_modules/canvas/build/Release/canvas.node', but app.allowRendererProcessReuse is true. See https://github.com/electron/electron/issues/18397.
    at process.func [as dlopen] (electron/js2c/asar.js:140)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196)
    at Object.func [as .node] (electron/js2c/asar.js:140)
    at Module.load (internal/modules/cjs/loader.js:981)
    at Module._load (internal/modules/cjs/loader.js:881)
    at Function.Module._load (electron/js2c/asar.js:769)
    at Module.require (internal/modules/cjs/loader.js:1023)
    at require (internal/modules/cjs/helpers.js:77)
    at Object.<anonymous> (/Users/Jeff/Document…s/lib/bindings.js:3)
    at Object.<anonymous> (/Users/Jeff/Document…s/lib/bindings.js:5)
```
Looks like it might be fixed by updating `init.cc` as described [here](https://github.com/electron/electron/issues/18397.)
```
NODE_MODULE(canvas, init);
```
to something like this...
```
#if NODE_MAJOR_VERSION >= 10
  NAN_MODULE_WORKER_ENABLED(canvas, init);
#else
  NODE_MODULE(canvas, init);
#endif
```

**Comment by zbjornson** [comment] 2020-11-12 22:07
Right, duplicate of #1394.

**Closed by zbjornson** 2020-11-12 22:07 UTC
