### ISSUE TITLE
When using `drawImage` my `svg` canvas results in an embedded PNG

### ISSUE THREAD

**Issue by EdenCoder** [Automattic/node-canvas#1144] opened 2018-04-18 12:03 UTC
`ctx.drawImage (Image, x, y, height, width);` of an svg `createCanvas` converts the resulting `svg` to an embedded base64 png.

## Issue or Feature
When using `drawImage` my `svg` canvas results in an embedded PNG rather than a properly formatted XML `svg`.

## Steps to Reproduce
1. install canvas@next
2. create svg canvas
3. use ctx.drawImage using any image
4. check source of resulting svg (will be just a single embedded svg)

## Your Environment
Ubuntu zesty
node v9.0
canvas alpha.11

**Comment by zbjornson** [comment] 2018-04-18 15:26
There's no way for this library to convert a raster image to an SVG for you. Is that what you were trying to do? Can you provide an actual code example?

**Comment by zbjornson** [comment] 2018-06-25 23:55
Closing since there was no reply, and I think this is working as intended.

**Closed by zbjornson** 2018-06-25 23:55 UTC
Labels: Needs more info

**Comment by bimohxh** [comment] 2020-10-26 09:59
this is useful, when I load a svg to current canvas, and when I export to svg file type, why use base64 data image but not svg nest?

**Comment by a-dpq** [comment] 2021-11-21 21:17
I'm having the same problem, I think. I'm not loading an SVG. I'm exporting the canvas to SVG, but the result is an SVG with an embedded PNG. Weirdly, this only happens with some outputs of my program. Perhaps it defaults to embedding a PNG when it can't translate some of the drawing operations on the canvas into their corresponding SVG counterparts?
