### ISSUE TITLE
Canvas.registerFont is not a function

### ISSUE THREAD

**Issue by SomeoneCares11** [Automattic/node-canvas#878] opened 2017-02-24 21:40 UTC
Why i'm getting this error, i just installed canvas via npm install canvas
and i update the canvas using clone

```
root@ns3484799:/home/ProBot/node_modules/canvas/examples# node font.js
/home/ProBot/node_modules/canvas/lib/canvas.js:83
  return Canvas._registerFont(fs.realpathSync(src), fontFace);
                ^

TypeError: Canvas._registerFont is not a function
    at Function.Canvas.registerFont (/home/ProBot/node_modules/canvas/lib/canvas.js:83:17)
    at Object.<anonymous> (/home/ProBot/node_modules/canvas/examples/font.js:13:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

```

**Comment by chearon** [comment] 2017-02-24 23:54
It's not released yet, `Canvas.registerFont` is a part of 2.0 but that hasn't been published to NPM yet. See the end of #743

**Comment by beheh** [comment] 2017-02-28 12:41
Duplicate of #828.

**Closed** 2017-02-28 15:48 UTC

**Comment by ryuukibeat** [comment] 2017-07-15 16:23
I got this issue. I install this package with `npm install Automattic/node-canvas` so it's downloading the v2.0, right?
```
TypeError: Canvas.registerFont is not a function
```
Then I tried to commend that line, but I got this new error
```
TypeError: Canvas is not a constructor
```
What happen? can I go wrong from the require() ?

This is my code:
```javascript
const Canvas = require('canvas');
const path = require('path');

const Image = Canvas.Image;
// Canvas.registerFont(path.join(__dirname, '..', '..', 'assets', 'fonts', 'BackIssuesBB_reg.ttf'), { family: 'BackIssuesBB' });

const canvas = new Canvas(530, 391);
const ctx = canvas.getContext('2d');
```
Thanks in advance.

**Comment by LinusU** [comment] 2017-07-15 17:35
It's because the interface have changed on the latest master, and unfortunately registerFont is temporarily broken. You can try to install the latest alpha instead

**Comment by ryuukibeat** [comment] 2017-07-15 23:54
Thank you. I think it's worked now, but got this warning issues instead
```
(node.exe:19652): Pango-WARNING **: couldn't load font "sans serif Not-Rotated 10px", falling back to "Sans Not-Rotated 10px", expect ugly output.

(node.exe:19652): Pango-WARNING **: couldn't load font "sans serif 10px", falling back to "Sans 10px", expect ugly output.
```
from this code:
```js
Canvas.registerFont(path.join(__dirname, '..', '..', 'assets', 'fonts', 'BackIssuesBB_reg.ttf'), { family: 'Back Issues BB' });

ctx.font = '12px Back Issues BB';
ctx.fillStyle = '#131313';
ctx.fillText(line, 162, 100);
```
Canvas version: `v2.0.0-alpha.1`

**Comment by chearon** [comment] 2017-07-18 23:11
@ryuukibeat looks like it couldn't load your font, and then it couldn't load a fallback

Can you try loading a font like the one distributed [here](https://github.com/Automattic/node-canvas/tree/master/examples/pfennigFont) and see if that gives you the same problem?

The fallback isn't loading because you might need to change your `pango.aliases` file according to what you have available on Windows.

**Comment by ryuukibeat** [comment] 2017-07-18 23:16
@chearon Thank you, and sorry. What I mean is, the Canvas working properly and the fonts registered/loaded. But I don't know why the warning shows up.

So, it's cool. As long as it's worked. Thank you.
