### ISSUE TITLE
Inspecting canvas object in node-inspector crashes node

### ISSUE THREAD

**Issue by hura** [Automattic/node-canvas#258] opened 2013-02-21 23:23 UTC
If I hook up node-inspector I can step through the code fine but as soon as I 'inspect' a canvas object it'll crash:

    .node-gyp/0.8.6/src/node_object_wrap.h:52: static T* node::ObjectWrap::Unwrap(v8::Handle<v8::Object>) [with T = Canvas]: Assertion `handle->InternalFieldCount() > 0' failed.

Minimal working example should be a simple:

    var Canvas = require('canvas')
    var canvas = new Canvas(w,h)

**Comment by chylvina** [comment] 2015-02-28 09:14
+1

**Comment by dfoody** [comment] 2015-07-16 02:38
+1 on io.js 2.3.4 with canvas 1.2.3

**Comment by hometlt** [comment] 2016-02-02 23:26
+1

**Comment by LinusU** [comment] 2016-02-15 20:36
Duplicate of #76

**Closed by LinusU** 2016-02-15 20:36 UTC

**Comment by DaviesGit** [comment] 2018-07-31 02:39
+1

**Comment by LinusU** [comment] 2018-07-31 09:04
@DaviesGit this was fixed by #808
