### ISSUE TITLE
getContext("2d") extremely slow, 12+ seconds 

### ISSUE THREAD

**Issue by daz** [Automattic/node-canvas#1444] opened 2019-06-09 09:32 UTC
Apologies if this has been answered, I couldn't find any previous issues.

```js
const { createCanvas } = require("canvas");
const canvas = createCanvas(10, 10);
const ctx = canvas.getContext("2d");
```

Running this takes ~12 seconds, yet instant if I remove the last line.

    › time node index.js   
    node index.js  10.76s user 0.27s system 82% cpu 13.451 total

macOS Mojave 10.14.5
Node v12.4.0
canvas@HEAD or 2.5.0, both slow

Is this normal?

**Comment by zbjornson** [comment] 2019-06-09 17:04
This sounds maybe like #1358... you could try some of the steps in that issue to see if it is indeed slow dynamic linking, but there's no solution posted there (I don't know what a solution would be) and 12 seconds is really, really slow... Do you have a virus scanner that might be locking files or something?

Possible that a static build would work around it (not a straightforward change).

**Comment by Riccsson** [comment] 2021-02-02 20:49
I have the same problem with the canvas.GetContext().
I am using Three.js that runs the getContext in the constructor of THREE.WebGLRenderer and it takes 10 seconds according to the profiler in Microsoft Edge browser, and 4 seconds in Firefox.

**Comment by zbjornson** [comment] 2022-03-19 19:47
@Riccsson if that's in a web browser, that's not a node-canvas issue.

I don't think there's anything actionable here. This is most likely a duplicate of #1358.

**Closed by zbjornson** 2022-03-19 19:47 UTC
