### ISSUE TITLE
Trying to install 32-bit Win version canvas module on MS Azure App Service. I'm using local 64-bit version Win Environment and trying to create 32-bit version canvas module.

### ISSUE THREAD

**Issue by niksocial17** [Automattic/node-canvas#1434] opened 2019-06-05 12:15 UTC
Hi, 

I followed an instructions to create 32-bit version npm canvas module by referring the following url.
https://github.com/Automattic/node-canvas/wiki/Installation:-Windows 

But, still I see an error on MS Azure App Service environment for support of this module.
![azure app service error - canvas module](https://user-images.githubusercontent.com/50211147/58955933-2c89f580-876b-11e9-965d-e6ba4d7327e2.jpg)

Could you please guide me to create safer 32-bit version of this module on local Win64 bit enviroment. 

Looking forward to hear from you.

Thanks.

**Comment by zbjornson** [comment] 2019-06-05 17:08
See #1375 (identical to this issue) and #704 (regarding 32-bit builds). Unfortunately I don't know of an available solution. It is likely easier to use a 64-bit Azure env is possible (https://stackoverflow.com/a/48252944/1218408).

Closing as a dupe of #1375, feel free to discuss more there.

**Closed by zbjornson** 2019-06-05 17:08 UTC

**Comment by niksocial17** [comment] 2019-06-05 19:10
can I get this module for Win32 environment?

It would be great if you provide us. 

Thanks.
