### ISSUE TITLE
Code stops without throwing an error

### ISSUE THREAD

**Issue by Aci-yt** [Automattic/node-canvas#1321] opened 2018-12-09 17:04 UTC
So I wanted to start using canvas, and followed this (https://discordjs.guide/#/popular-topics/canvas) tutorial. I didn't use the code 1:1, but had multiple people verify that my code **should** work, but doesn't.

Whenever it gets to this line: `const background = await Canvas.loadImage('./encounter.png');`, my code stops without any errors, as if I stopped the bot myself. I tired catching an error with `.catch()`, didn't work. I also tried `try{}catch{}`, which didn't help either.
After I asked in the Discord.js and Coding Den Discord servers I was told to ask here, since they assumed that it's an error with canvas itself. 
Any other commands which are unrelated to canvas work, which leads me to the same conclusion.

(And yes, the image "encounter.png" does exist in the specified path)

This is my code: 
```js
const Discord = require('discord.js');
const Canvas = require('canvas');
const snekfetch = require('snekfetch');
const config  = require("./config.json")
const bot = new Discord.Client();

bot.on('ready', () => {
	console.log('Ready!');
});

bot.on('message', async message => {
    
const args = message.cleanContent.slice(config.prefix2.length).trim().split(/ +/g);
const cmd = args.shift().toLowerCase();

if (cmd =="doit"){
	try{
		const canvas = Canvas.createCanvas(700, 250);
		// ctx (context) will be used to modify a lot of the canvas
		const ctx = await canvas.getContext('2d');
		// Since the image takes time to load, you should await it
		const background = await Canvas.loadImage('./encounter.png').catch((error) => console.log(error))
		// This uses the canvas dimensions to stretch the image onto the entire canvas
		ctx.drawImage(background, 0, 0, canvas.width, canvas.height);
		// Use helpful Attachment class structure to process the file for you
		const attachment = new Discord.Attachment(canvas.toBuffer(), 'welcome-image.png');
	
		message.channel.send(`Welcome to the server, ${message.author.id}!`);

	} catch(error){
		console.log(error)
	}
}

});
bot.login(config.token2);
```

-I'm using Visual Studio Code on Windows 10
-Its not running off of a batch-file
-The canvas version I'm using is canvas@2.0.1

Thanks in advance,
Aci

**Comment by Hakerh400** [comment] 2018-12-09 18:09
Able to reproduce segfault on Node.js v11.2.0 and node-canvas 2.2.0 using the following code

```js
new Image().src = Buffer.from('89504E470D', 'hex');
```

Can you please share `encounter.png` file to make sure this is the same issue.

**Comment by meyfa** [comment] 2018-12-11 01:07
I'm experiencing the same behavior with this very minimal setup:

```javascript
const { createCanvas } = require("canvas");

console.log("before");
const canvas = createCanvas(1000, 1000);
console.log("after");
```

Output:

```sh
$ node canvastest.js
before
```

As you can see, `after` is never logged, the process just stops, no errors. Surprisingly, if I lower the canvas size to 200x1000, it does work — but not for larger dimensions.

I'm not completely sure this is the same issue, it just looks very much related! If not, I'll be happy to submit it separately.

I'm running canvas 2.2.0 on node 8.11.2 on Windows 10.

**Comment by Hakerh400** [comment] 2018-12-12 12:47
@Acituanbus I cannot reproduce crash using your image. What is the Node.js exit code
(output of `echo %errorlevel%`)?

@meyfa Your issue seems unrelated to PNG (and I cannot reproduce it). It's weird that your code crashes the process, since creating canvas doesn't actually allocate anything until a surface is obtained. Does it crash on `createCanvas` , or `getContext('2d')`? What is the process exit code (errorlevel)?

**Comment by meyfa** [comment] 2018-12-12 12:51
@Hakerh400 As you can see from the code snippet, there is no call to `getContext`. It crashes on `createCanvas`. The exit code is `-1066598273`. When reducing the canvas size so that it doesn't crash, the exit code is `0`.

Shall I open a separate issue?

**Comment by Hakerh400** [comment] 2018-12-12 12:56
Thanks. According to the exit code, your issue is probably a duplicate of #1285. Please try upgrading to Node.js v8.12.0.

**Comment by meyfa** [comment] 2018-12-12 13:10
Thanks a lot, you were right! That did the trick.

**Comment by MrDrProfX** [comment] 2018-12-13 03:15
Same issue here, using firebase functions with node 8. 
```
loadImage(url).then(image => {
            let scale = size / image.width;
            console.log(`image size: ${image.width}`);
            ctx.scale(scale, scale);
            ctx.drawImage(image, 0, 0);
            encoder.addFrame(ctx);
        }).catch(err => {
            console.log('error loading image');
            console.warn(err.message);
        })
```
I get no errors or warnings, only timeout. I get no exit code in the logs that I'm aware of. Not sure what's up.

**Comment by Hakerh400** [comment] 2018-12-13 05:45
In case Node.js process is started from the console, the exit code can be obtained by typing `echo %errorlevel%` (on Windows) or `echo $?` on Linux and Mac in the console after Node.js process exits. In case of Visual Studio or other third-party application that launches Node.js, I'm not sure.

As said above, the issues reported here seem to be related to a bug in old Node.js v8.x versions. Please try upgrading to Node.js v8.12.0 and see if the bug persists.

**Comment by MrDrProfX** [comment] 2018-12-13 18:31
Okay for me, the issue was the url I passed the loadImage function was an array containing a single string (the url):

`['https://mysite.com/myimage.jpeg']`.
Whoops. Url should be just:
`'https://mysite.com/myimage.jpeg'`.

I recommend double checking the data type being passed in to the loadImage function. Should be a string. Best of luck!

**Comment by Acituanbus** [comment] 2018-12-15 17:11
Alright, so I just checked and THIS code works just fine:
```js
if (cmd =="doit"){
	try{
		const canvas = Canvas.createCanvas(256, 256);
		// ctx (context) will be used to modify a lot of the canvas
		const ctx = await canvas.getContext('2d');
		// Since the image takes time to load, you should await it
		const background = await Canvas.loadImage('https://i.imgur.com/6BCuej8.png').catch((error) => console.log(error))
		// This uses the canvas dimensions to stretch the image onto the entire canvas
		ctx.drawImage(background, 0, 0, canvas.width, canvas.height);
		// Use helpful Attachment class structure to process the file for you
		const attachment = new Discord.Attachment(canvas.toBuffer(), 'welcome-image.png');
	
		message.channel.send(`Welcome to the server, ${message.author.id}!`);

	} catch(error){
		console.log(error)
	}
}
```
but when I replace the imgur url with this one: 
`https://i.imgur.com/11bjsFz.png` it crashes without an error
Any idea why? Can images not be transparent?

**Comment by Acituanbus** [comment] 2018-12-16 08:09
Alright, though I have no experience with ffmpeg and no idea how it works, I'll see if I can figure it out
Thanks!

**Comment by Hakerh400** [comment] 2018-12-16 19:18
@Acituanbus Can you please run the following code and post the full output.

```js
const Canvas = require('canvas')
console.log(process.version)
for(var key in Canvas)
if(/version$/i.test(key))
console.log(`${key}: ${Canvas[key]}`)
```

@zbjornson Tested using latest Cairo version 1.16.0 and it properly handles sRGB, cHRM and similar chunks, and also throws proper error on the missing IEND chunk (loads properly #73 and #122 and catches #1324 error). If you can confirm it, we may close the linked issues (including this one, if it turns out to be outdated cairo) as fixed and suggest updating cairo.

**Comment by Acituanbus** [comment] 2018-12-20 20:48
I did, this was the output:
```js
version: 2.0.1
test.js:35
cairoVersion: 1.15.12
test.js:35
jpegVersion: 8
test.js:35
gifVersion: 5.1.4
test.js:35
freetypeVersion: 2.9.1
```

**Comment by Acituanbus** [comment] 2018-12-29 09:36
So any idea?

**Comment by zbjornson** [comment] 2019-01-20 23:07
@Acituanbus the two imgur links are dead, but the image you posted in https://github.com/Automattic/node-canvas/issues/1321#issuecomment-445559496 loads successfully for me on Win 10 with canvas v2.0.1 and v2.3.1. Does that image work for you? If not, can you please upload the failing image here?

**Comment by kemosaf** [comment] 2020-06-01 07:01
> Alright, so I just checked and THIS code works just fine:
> 
> ```js
> if (cmd =="doit"){
> 	try{
> 		const canvas = Canvas.createCanvas(256, 256);
> 		// ctx (context) will be used to modify a lot of the canvas
> 		const ctx = await canvas.getContext('2d');
> 		// Since the image takes time to load, you should await it
> 		const background = await Canvas.loadImage('https://i.imgur.com/6BCuej8.png').catch((error) => console.log(error))
> 		// This uses the canvas dimensions to stretch the image onto the entire canvas
> 		ctx.drawImage(background, 0, 0, canvas.width, canvas.height);
> 		// Use helpful Attachment class structure to process the file for you
> 		const attachment = new Discord.Attachment(canvas.toBuffer(), 'welcome-image.png');
> 	
> 		message.channel.send(`Welcome to the server, ${message.author.id}!`);
> 
> 	} catch(error){
> 		console.log(error)
> 	}
> }
> ```
> 
> but when I replace the imgur url with this one:
> `https://i.imgur.com/11bjsFz.png` it crashes without an error
> Any idea why? Can images not be transparent?

Niceeeeeeeeeeeeeeee ty, this helped

**Closed** 2022-03-19 19:44 UTC
Labels: Needs more info
