### ISSUE TITLE
node_modules/canvas/build/Release/canvas.node: invalid ELF header

### ISSUE THREAD

**Issue by sigorilla** [Automattic/node-canvas#1000] opened 2017-09-13 12:44 UTC
If I try install `node-canvas` in docker, so I get error. Packages `build-essential`, `g++`, `libcairo2-dev`, `libgif-dev`, `libjpeg8-dev`, `libpango1.0-dev` are installed.

In running container installation is working correctly.

## Issue

Node failed with error:

```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /usr/local/www/node_modules/canvas/build/Release/canvas.node: invalid ELF header
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/www/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Installation log:

```

> canvas@1.5.0 install /usr/local/www/node_modules/canvas
> node-gyp rebuild

make: Entering directory `/usr/local/www/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
../src/Canvas.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE Canvas::ToBuffer(Nan::NAN_METHOD_ARGS_TYPE)':
../src/Canvas.cc:326:14: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/6.9.5/include/node/v8.h:6771): Use isolate version [-Wdeprecated-declarations]
     TryCatch try_catch;
              ^
../src/Canvas.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamPNGSync(Nan::NAN_METHOD_ARGS_TYPE)':
../src/Canvas.cc:418:12: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/6.9.5/include/node/v8.h:6771): Use isolate version [-Wdeprecated-declarations]
   TryCatch try_catch;
            ^
../src/Canvas.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE Canvas::StreamJPEGSync(Nan::NAN_METHOD_ARGS_TYPE)':
../src/Canvas.cc:537:12: warning: 'v8::TryCatch::TryCatch()' is deprecated (declared at /root/.node-gyp/6.9.5/include/node/v8.h:6771): Use isolate version [-Wdeprecated-declarations]
   TryCatch try_catch;
            ^
./Release/.deps/Release/obj.target/canvas/src/Canvas.o.d.raw { dev: 53,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 25041,
  size: 7407,
  blocks: 16,
  atime: 2017-09-13T11:06:28.000Z,
  mtime: 2017-09-13T11:06:28.000Z,
  ctime: 2017-09-13T11:06:28.449Z,
  birthtime: 2017-09-13T11:06:28.449Z }
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
./Release/.deps/Release/obj.target/canvas/src/CanvasGradient.o.d.raw { dev: 53,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 25045,
  size: 6567,
  blocks: 16,
  atime: 2017-09-13T11:06:29.000Z,
  mtime: 2017-09-13T11:06:29.000Z,
  ctime: 2017-09-13T11:06:29.608Z,
  birthtime: 2017-09-13T11:06:29.608Z }
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
./Release/.deps/Release/obj.target/canvas/src/CanvasPattern.o.d.raw { dev: 53,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 25048,
  size: 6564,
  blocks: 16,
  atime: 2017-09-13T11:06:30.000Z,
  mtime: 2017-09-13T11:06:30.000Z,
  ctime: 2017-09-13T11:06:30.617Z,
  birthtime: 2017-09-13T11:06:30.617Z }
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
../src/CanvasRenderingContext2d.cc: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE Context2d::GetImageData(Nan::NAN_METHOD_ARGS_TYPE)':
../src/CanvasRenderingContext2d.cc:802:71: warning: 'v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const' is deprecated (declared at /root/.node-gyp/6.9.5/include/node/v8.h:3269): Use maybe version [-Wdeprecated-declarations]
   Local<Object> instance = cons->GetFunction()->NewInstance(argc, argv);
                                                                       ^
./Release/.deps/Release/obj.target/canvas/src/CanvasRenderingContext2d.o.d.raw { dev: 53,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 25050,
  size: 7235,
  blocks: 16,
  atime: 2017-09-13T11:06:33.000Z,
  mtime: 2017-09-13T11:06:33.000Z,
  ctime: 2017-09-13T11:06:33.164Z,
  birthtime: 2017-09-13T11:06:33.164Z }
  CXX(target) Release/obj.target/canvas/src/color.o
./Release/.deps/Release/obj.target/canvas/src/color.o.d.raw { dev: 53,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 25052,
  size: 70,
  blocks: 8,
  atime: 2017-09-13T11:06:33.000Z,
  mtime: 2017-09-13T11:06:33.000Z,
  ctime: 2017-09-13T11:06:33.624Z,
  birthtime: 2017-09-13T11:06:33.624Z }
  CXX(target) Release/obj.target/canvas/src/Image.o
./Release/.deps/Release/obj.target/canvas/src/Image.o.d.raw { dev: 53,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 25054,
  size: 6522,
  blocks: 16,
  atime: 2017-09-13T11:06:34.000Z,
  mtime: 2017-09-13T11:06:34.000Z,
  ctime: 2017-09-13T11:06:34.932Z,
  birthtime: 2017-09-13T11:06:34.932Z }
  CXX(target) Release/obj.target/canvas/src/ImageData.o
./Release/.deps/Release/obj.target/canvas/src/ImageData.o.d.raw { dev: 53,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 25056,
  size: 6537,
  blocks: 16,
  atime: 2017-09-13T11:06:35.000Z,
  mtime: 2017-09-13T11:06:35.000Z,
  ctime: 2017-09-13T11:06:35.921Z,
  birthtime: 2017-09-13T11:06:35.921Z }
  CXX(target) Release/obj.target/canvas/src/init.o
./Release/.deps/Release/obj.target/canvas/src/init.o.d.raw { dev: 53,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 25058,
  size: 7180,
  blocks: 16,
  atime: 2017-09-13T11:06:36.000Z,
  mtime: 2017-09-13T11:06:36.000Z,
  ctime: 2017-09-13T11:06:36.790Z,
  birthtime: 2017-09-13T11:06:36.790Z }
  CXX(target) Release/obj.target/canvas/src/FontFace.o
./Release/.deps/Release/obj.target/canvas/src/FontFace.o.d.raw { dev: 53,
  mode: 33188,
  nlink: 1,
  uid: 0,
  gid: 0,
  rdev: 0,
  blksize: 4096,
  ino: 25060,
  size: 7052,
  blocks: 16,
  atime: 2017-09-13T11:06:37.000Z,
  mtime: 2017-09-13T11:06:37.000Z,
  ctime: 2017-09-13T11:06:37.869Z,
  birthtime: 2017-09-13T11:06:37.869Z }
  SOLINK_MODULE(target) Release/obj.target/canvas.node
  COPY Release/canvas.node
make: Leaving directory `/usr/local/www/node_modules/canvas/build'


```

## Steps to Reproduce

```js
var Canvas = require('canvas');
```

```sh
node index.js
```

## Your Environment
* Version of node-canvas: 1.5.0
* Environment: node 6.9.5 on Trusty Ubuntu
* Docker: 17.06.2-ce

**Comment by zbjornson** [comment] 2017-09-14 03:08
Did you build on the same platform that you're trying to load it from? That error (usually?) means it was built on one architecture and then moved to another.

**Comment by schuylr** [comment] 2017-11-02 15:47
I encountered this error and it was because I run `npm install` within my Dockerfile, but in my local environment, my `docker-compose.yml` has the application directory mapped to my host machine's development directory. Therefore my `npm install`ed node modules from the host machine overwrote the container's modules.

I would close it on this basis, all worked after I deleted the contents of `node_modules` and re-ran `npm install` :)

**Comment by LinusU** [comment] 2017-11-02 16:03
Yeah, seems like the problem is that the node_modules from the host machine was used. Closing but feel free to reopen if it was something else 👌

**Closed by LinusU** 2017-11-02 16:03 UTC

**Comment by jamesamurr-bind** [comment] 2019-05-25 00:11
I'm running into the same issue now as well. It happened because I installed modules locally, but have to deploy those dependencies to aws lambda. Any way around this? As far as I know you have to manually upload the dependencies.

**Comment by LinusU** [comment] 2019-05-27 13:07
> It happened because I installed modules locally, but have to deploy those dependencies to aws lambda. Any way around this?

You can see how I did it in my tool [Scandium](https://github.com/LinusU/scandium) here, it's installing dependencies & building in a docker container, so that native module works. You should be able to do something similar, or just use that tool...

**Comment by gagangoku** [comment] 2023-02-15 17:42
In my case I had to add node_modules to the .dockerignore file
