### ISSUE TITLE
Do not display emojis via fillText()

### ISSUE THREAD

**Issue by LukyVj** [Automattic/node-canvas#614] opened 2015-08-24 23:03 UTC
Hi, wonderful script you go here. 

I came across a problem recently, I wanted to turn a string containing an Apple emoji in it, into a canvas, and then apply a `toDataURL()` on it, but the emoji just got ignored. 

I tested the code on regular canvas, directly in a html page, and it works. 
It seems that only the node-canvas version is buggy. 

It'll be awesome if someone on your side, could try to get them supported.
Any fix would be appreciated, Thanks :)

**Comment by vegeta897** [comment] 2016-01-19 20:59
Encountered this issue as well. Emoji work fine in browser canvas, but not node-canvas.

**Comment by LinusU** [comment] 2019-01-11 16:45
duplicate of #760

**Closed by LinusU** 2019-01-11 16:45 UTC
Labels: Help wanted, Text & Fonts
