### ISSUE TITLE
How do we register font via a URL or Node buffer?

### ISSUE THREAD

**Issue by pranavburnwal** [Automattic/node-canvas#2291] opened 2023-09-22 06:38 UTC
## Issue/Feature - Unsure
- [*] If this is an issue with installation, I have read the [troubleshooting guide](https://github.com/Automattic/node-canvas/issues/1511).

How do we register font via a URL or Node buffer?

## Steps to Reproduce

```js
var Canvas = require('canvas');
var canvas = Canvas.createCanvas(200, 200);
var ctx = canvas.getContext('2d');
// etc.
```

## Your Environment
* Version of node-canvas (output of `npm list canvas` or `yarn list canvas`): Latest stable on npm.
* Environment (e.g. node 4.2.0 on Mac OS X 10.8): Linux and Mac M_

**Comment by zbjornson** [comment] 2023-12-28 22:30
This isn't supported right now. You'd have to fetch the URL or save the buffer to a file first. See #386: these features appear to require replacing Pango.

Closing as a dupe of that issue.

**Closed by zbjornson** 2023-12-28 22:30 UTC
